### ISSUE TITLE
cannot build (linux_x86_64)

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#1]
Hi
I'm new to Github so I'm not sure raising an "issue" is the best way to handle my problem. Please tell me if I'm doing things wrong!

I have several problems when trying to build from this repo

1. When trying to build "tuxguitar-linux-swt-x86_64" there is an unresolved dependency to _org.eclipse.swt.gtk.linux.x86_64:jar:4.13_
Rolling back the expected version to 4.6.1 in pom.xml file in root folder solves the issue. v4.6.1 was the version used by tuxguitar 1.5.6.

It's always a bit frustrating to roll things back, but if I don't do it I just can't build/run. Possibly a problem in my environment?

2. These new build scripts introduce a dependency to "docbook-to-man" binary. I could easily find a deb package, but it does not seem so simple in rpm-based distros (I'm running OpenSuse tumbleweed). I only found a rpm package that does not install because of broken dependencies (package seems inconsistent).
Is it somehow possible to remove this dependency? Or is there a reliable rpm package available somewhere?

best regards,
guiv

**Comment by guiv42** [comment]
Solution to problem 1 is [here](https://github.com/pterodactylus42/tuxguitar-2.0beta/issues/2)
Need to download manually the dependency from eclipse, then to provide it explicitly to maven with command
`mvn install:install-file -Dfile=<absolute path to your swt download>/swt-4.13-gtk-linux-x86_64/swt.jar -DartifactId=org.eclipse.swt.gtk.linux.x86_64 -Dpackaging=jar -DgroupId=org.eclipse.swt -Dversion=4.13`

**Comment by helge17** [comment]
1. 827c57a adds my build script. You can't use it right away, but you might find some useful hints to help you build Tuxguitar.
2. e378ecf removes the dependency on docbook-to-man.

**Comment by guiv42** [comment]
Works great, thank you very much!
