### ISSUE TITLE
Description truncated in skin settings dialog

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#119]
When opening the Tools -> Settings -> Skins dialog, the skin description is initially displayed correctly:

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/f05f5780-81fe-464e-aa48-0ea5a4f811c3)

When you switch to a skin with a longer description, the text is truncated where the lines of the initially selected skin ended:

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/a83dab24-6349-4fd0-96ed-d2a0be19f623)

This happens with both SWT and JFX.

**Comment by guiv42** [comment]
looks it's been introduced by c83e137612f7e7ea83a3801f0379cc33495ae5dd

**Comment by helge17** [comment]
Sorry, you are right. Without https://github.com/helge17/tuxguitar/commit/c83e137612f7e7ea83a3801f0379cc33495ae5dd, the problem is still there, but much smaller, the strings are truncated by only ~two letters:

**SWT**, without c83e137612f7e7ea83a3801f0379cc33495ae5dd:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/482e6733-80fc-4cdd-9f1c-2c5adfe22a9c)
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/258d93b8-3554-45ea-8c0c-98673a71cfe4)

**JFX**, without c83e137612f7e7ea83a3801f0379cc33495ae5dd:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/c87c025d-8b99-4b45-baaa-1877e037a223)
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/acb42a3c-96c1-43d0-9b5a-0e2e2aa1422a)

Some background: I was thinking about how TuxGuitar behaves when we start deleting old skins. For example, if you delete Breeze (I tested with Breeze because the description is quite short) and the user had Breeze as active skin, the dialog looks like this:

**SWT**, without c83e137612f7e7ea83a3801f0379cc33495ae5dd:

`$ rm -r /opt/tuxguitar/share/skins/Breeze/`

Then start TuxGuitar.

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/a88e6942-1ede-4a2a-81b9-cf73475ae991)
Select skin Symbolic:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/01828c34-26f1-45b9-800b-83fcfe5154ed)
Switch to blue_serious:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/8b4af97a-76f5-4e39-8651-98dbe4483908)
In this case, the description is heavily truncated, even without c83e137612f7e7ea83a3801f0379cc33495ae5dd.

Now the GUI looks ugly anyway when the selected skin is deleted, but that's another problem I was going to look at later.

I hope this explains a little why I worked on this dialog. If it gets too complicated, I will revert c83e137612f7e7ea83a3801f0379cc33495ae5dd, close this topic and maybe try another way.

**Comment by guiv42** [comment]
Okay. I understand you want to handle the case of a user switching to a more recent version of TuxGuitar, where his configured skin was deleted. Correct?
In this case, at init it should be detected that user parameter is now invalid, and then switch to default skin. So the case of the empty drop-down list selection above should never occur I think.
Or possibly if the user manually interferes with config folder content, but in this case so many things could go wrong I would not bother too much.

I see 2 possible options to fix this:
1. when dialog opens, loop over available skins, look for the longest strings, and set labels' sizes accordingly
2. when user selection in drop-down list changes, adjust dynamically labels' sizes to the newly selected strings

I don't know which one is simplest, none looks trivial to me. I will have a look. Or can you think of a better solution?

**Comment by helge17** [comment]
Thanks for the patch, @guiv42, dialog looks good now!

> Okay. I understand you want to handle the case of a user switching to a more recent version of TuxGuitar, where his configured skin was deleted. Correct?

Exactly.

> In this case, at init it should be detected that user parameter is now invalid, and then switch to default skin. So the case of the empty drop-down list selection above should never occur I think.
> Or possibly if the user manually interferes with config folder content, but in this case so many things could go wrong I would not bother too much.

I also thought about checking if the selected skin is still present at startup, and switching to the default skin if it is not. But to be honest, I have not been able to implement this yet.

A second idea is to use the icon from the default skin when the icon is missing from the selected skin. If the selected skin was deleted, the user would actually see the default skin until they switch to another skin. This would add the possibility to create "translucent" skins where you only need to add the icons you want to change. The following code would accomplish this:

```
diff --git a/TuxGuitar/src/org/herac/tuxguitar/app/util/TGFileUtils.java b/TuxGuitar/src/org/herac/tuxguitar/app/util/TGFileUtils.java
index 167c87b9..c4ed3868 100644
--- a/TuxGuitar/src/org/herac/tuxguitar/app/util/TGFileUtils.java
+++ b/TuxGuitar/src/org/herac/tuxguitar/app/util/TGFileUtils.java
@@ -122,7 +122,12 @@ public class TGFileUtils {
 			if( stream != null ){
 				return uiFactory.createImage(stream);
 			}
-			System.err.println(name + ": not found");
+			stream = TGResourceManager.getInstance(context).getResourceAsStream("skins/" + "Oxygen" + "/" + name);
+			if( stream != null ){
+				System.err.println(name + ": not found in skin " + skin + ", using icon from the default skin Oxygen.");
+				return uiFactory.createImage(stream);
+			}
+			System.err.println(name + ": not found in skin " + skin + " and the default skin Oxygen.");
 		}catch(Throwable throwable){
 			throwable.printStackTrace();
 		}
```
("Oxygen" needs to be replaced by something like `getDefaults().getValue(TGConfigKeys.SKIN)`)

But I'm not sure that would be a good idea. What do you think?

**Comment by guiv42** [comment]
I would consider the 2 options as independent.

I think it is mandatory to switch to default skin at init if user configured value is invalid. Globally this logic should apply for all user parameters, and this should ease the future evolution of the app (now that the config folder is no more lost at each app update). I will have a look at a possible implementation for that. The idea would be similar to f6ea4a599af97f6abe67efaabbd49123ee3a1f80: load default, then override by user-defined value *if valid*

About the degraded mode you suggest when an image is not found, I don't know... There are pros and cons.
If for some reason there is an error in one skin (missing image, misspelled filename, corrupted file...) this should add some robustness and mask the problem to the user. At least in this case I would keep the `System.err.print` statement, to ease troubleshooting.
On the other hand, if the problem concerns the skin name, or the preview image, this could lead to inconsistent display in the SkinOption dialog.

**Comment by guiv42** [comment]
With PR #129 the configured skin should be replaced by default value if it does not exist any more when opening TG. I could not implement it exactly as mentioned above. Instead: name of configured skin is loaded from config, then when trying to load skin it is overwritten by default if the associated skin is not found (checking if skin attribute "name" is defined).
I tried the scenario of user configured skin deletion, TG opens with Oxygen, skinOption dialog shows "Oxygen" attributes and preview, and user config file is updated

**Comment by helge17** [comment]
Thank, patches work great!
