### ISSUE TITLE
released sources have incorrect version attribute

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#125]
In 1.6.0 released source archive, modules have an attribute *version* set to "SNAPSHOT" in their pom files.
Context: I'm trying to build a rpm package for OpenSuse distro from this source archive. I can currently build a  package, but:
- outputs of maven build step are located in a folder `xxx-SNAPSHOT-` (not logical, but minor)
- at rpm installation the package manager GUI shows package content, with all modules versions set to SNAPSHOT. From user point of view it's not fantastic.

See what it looks like when I update from 1.5.4 to 1.6.0 (truncated screenshot):
![Screenshot_20230930_175307](https://github.com/helge17/tuxguitar/assets/129443524/9614f9b4-b7c4-4ac2-8418-457708be0c0f)

I tried to patch all pom files prior to build (from rpmbuild), it's a bit complex and I did not succeed (yet).

For future releases it would be cleaner if the released sources include correct modules versions.
I don't fully understand the build&release process, especially how the source archive is built, so I have no idea how to do this.
It does not seem realistic to me to update each pom file before each delivery, that would require to revert everything (from version to SNAPSHOT) after.
Could there be a way to define an attribute in top-level pom (or another file), and to re-use it from each "child" pom? So that one single file would require an update?

**Comment by helge17** [comment]
The source archives are automatically generated by Github when you release a new version. I don't know if there is a way to prevent that.

I built the binary package 1.6.0 with the command

`./misc/build_tuxguitar_from_source.sh -r SRC -A`

The script makes some changes to the source code before starting `mvn`, essentially replacing the SNAPSHOT string with the build version, in this case 1.6.0; see the `prepare_source` function.

Julian has done something similar in his builds, see https://sourceforge.net/p/tuxguitar/code/HEAD/tree/trunk/build-scripts/tuxguitar-src/build.xml#l150

>  Could there be a way to define an attribute in top-level pom (or another file), and to re-use it from each "child" pom? So that one single file would require an update?

Would be nice, sure. I'll put it on my TODO list, but I'm not sure if I'll be able to implement this.

**Comment by guiv42** [comment]
Thanks for your feedback. So I will insist a bit more, trying to see if I can mimic your build script from rpmbuild spec file. Not so easy, as I cannot find any consistent documentation (especially for the maven plugin for rpmbuild).
Anyway, don't consider this a high priority

**Comment by guiv42** [comment]
Thank you @helge17 for the tip (link to your build script), that did the trick :)
So don't bother trying to modify anything, that's fine.
I can now build locally a rpm in a very similar way the 1.5.4 was built by OpenSUSE. So the next step for me is to learn how the OpenSUSE Build Service works, so that I can submit 1.6.0 (might take some time though)
