### ISSUE TITLE
Muted / dead note is not exported to ASCII properly

### ISSUE THREAD

**Issue by dasl-** [helge17/tuxguitar#126]
Hi there, thanks for continuing development on tuxguitar! It seems great so far :)

One small bug I noticed: if I have a muted / dead note (`x`), then when the tab is exported to ASCII format, the muted note will be exported as an open string (`0`). Here's how it looks in tuxguitar as the muted note:
<img width="236" alt="Screen Shot 2023-10-01 at 3 35 22 PM" src="https://github.com/helge17/tuxguitar/assets/1332576/9dfc8bc8-1b79-4e0a-be5c-499def4140f2">

But when exported to ASCII, it looks like this:
```
E|-2---2---2---2---2---2---2---2---|
B|-0---0---0---0---0---0---0---0---|
G|-0---0---0---0---0---0---0---0---|
D|-0---0---0---0---0---0---0---0---|
A|-0---0---0---0---0---0---0---0---|
E|-3---3---3---3---3---3---3---3---|
```

I think it would be better if it were exported like this instead:

```
E|-2---2---2---2---2---2---2---2---|
B|-0---0---0---0---0---0---0---0---|
G|-0---0---0---0---0---0---0---0---|
D|-0---0---0---0---0---0---0---0---|
A|-X---X---X---X---X---X---X---X---|
E|-3---3---3---3---3---3---3---3---|
```

TuxGuitar version: 1.6.0 macOS

**Comment by guiv42** [comment]
This one should be quite easy to fix, pull request coming soon

**Comment by guiv42** [comment]
@dasl- : this should be OK now
That would be nice if you can check this with the latest [pre-release](https://github.com/helge17/tuxguitar/releases), and close the issue if it's OK for you

**Comment by dasl-** [comment]
thank you! will verify when i get a chance.

**Comment by dasl-** [comment]
Verified, it works! Thanks again.
