### ISSUE TITLE
nice to have zoom (in, out and reset) in main toolbar

### ISSUE THREAD

**Issue by sugizo** [helge17/tuxguitar#141]
nice to have 
zoom button 
and sub button for zoom in, zoom out and zoom reset
in main toolbar

thanks and best regards

**Comment by guiv42** [comment]
Hi
the easiest way to zoom in/out is currently (Ctrl+mouse wheel) or (Ctrl+2fingers touchpad). From pre-release 2023-10-26 it is also possible to configure keyboard shortcuts.

From code perspective, adding buttons to the toolbar is fairly simple, it's already been done a few years ago on [SF](https://sourceforge.net/p/tuxguitar/patches/34/) (but not merged).
It seems to me the most complex part is to update the icons. Icons for "zoom in/out" can be found [here](https://github.com/brockdev/tuxguitar/tree/master/TuxGuitar/share/skins) (following link in SF post above), but:
- there is no icon for "zoom reset"
- icons are only available in png format, no vector graphics
- some work is needed to adapt to all skins (currently 9 skins are available)

If someone could provide some help for the icons, I can update the code.

**Comment by helge17** [comment]
@guiv42, if you update the code I'll care about the icons.

**Comment by sugizo** [comment]
why not adapt it like power tab, 
they don't use icon, 
but use percentage (%) instead, 
so user can type 
or 
scroll the percentage value they chosen

e.g. zoom = 125 % on powertab
![image](https://github.com/helge17/tuxguitar/assets/2418295/e875d77a-7a75-42be-b64f-d2d60db28080)

**Comment by guiv42** [comment]
I like the idea, but from software point of view it's much more complex. I already had a try a couple of months ago, and I finally abandoned (or at least postponed!). The software structure of the toolbar makes it easy to integrate buttons, but a significant rework is needed to integrate other widgets, like the one suggested above.
So I prefer to do it in 2 steps: simple adaptation first, and one day a complete rework of the toolbar (that might be an opportunity to also integrate player dialog in toolbar)

**Comment by helge17** [comment]
Thanks for the patch! I'll care about the Symbolic & Breeze Icons, previews etc. I think I will also replace the other zoom icons with the "original" ones from https://invent.kde.org/frameworks/oxygen-icons5/-/tree/master/22x22/actions/ But give me a few days, too much to do currently...

**Comment by guiv42** [comment]
Thanks
For sure this graphical edition task is really time consuming. But take your time, nothing's urgent.

**Comment by sugizo** [comment]
also nice to have info about zoom in/out shortcut in the drop down menu View
(Ctrl+mouse wheel) 
or 
(Ctrl+2fingers touchpad)

**Comment by guiv42** [comment]
Drop down menus display *keyboard* shortcuts, and only this type of shortcut. So, if you associate a key to these actions (through menu tools/shortcuts) this key will be displayed in the drop-down menu. It's not possible to display description of *mouse*-related controls there.
(Ctrl+mouse wheel) is a de facto standard for zoom in/out function in many applications, and 2-fingers touchpad is the way some systems replace the mouse wheel when no mouse is present.
I think the only place where these *mouse* controls can be documented is the "help" section (menu Help/Documentation)

**Comment by guiv42** [comment]
Feature is available since pre-release 2023-11-03.
@sugizo : ok to close this issue?

**Comment by helge17** [comment]
> Drop down menus display _keyboard_ shortcuts, and only this type of shortcut. So, if you associate a key to these actions (through menu tools/shortcuts) this key will be displayed in the drop-down menu. It's not possible to display description of _mouse_-related controls there. (Ctrl+mouse wheel) is a de facto standard for zoom in/out function in many applications, and 2-fingers touchpad is the way some systems replace the mouse wheel when no mouse is present. I think the only place where these _mouse_ controls can be documented is the "help" section (menu Help/Documentation)

Commit d54254ad7d1f43bb5db6eeb25426b2f0e5583098 adds a reference to the mouse wheel to the documentation. I also wanted to add the shortcuts Ctrl++ and Ctrl+- to zoom in and out, but shortcuts ending in + are not shown in the menu (Ctrl++, Shift++ etc). Looks like a bug in swt and jfx(?)

**Comment by sugizo** [comment]
for shortcut, agree with @guiv42 said above 

```
(Ctrl+mouse wheel) is a de facto standard for zoom in/out function in many applications, and 2-fingers touchpad is the way some systems replace the mouse wheel when no mouse is present.
I think the only place where these mouse controls can be documented is the "help" section (menu Help/Documentation)
```

since @helge17 already created the documentation for short cut

i'll close this issue, thanks n best regards
