### ISSUE TITLE
nice to have volume or velocity adjust bar to change it's value 

### ISSUE THREAD

**Issue by sugizo** [helge17/tuxguitar#144]
nice to have volume or velocity adjust bar to change it's value 
like in musescore

![image](https://github.com/helge17/tuxguitar/assets/2418295/41e833d0-33f4-45bc-bec2-7e7b84e563f7)

thanks and best regards

**Comment by sugizo** [comment]
power tab editor using this feature too, 
the feature is between the instrument name and the tuning (left bottom)

![278817171-e875d77a-7a75-42be-b64f-d2d60db28080](https://github.com/helge17/tuxguitar/assets/2418295/b1f0e69a-9905-43de-ac41-a2967069c4ec)

**Comment by guiv42** [comment]
I am currently working on this feature request. My conclusions so far:
- adding *track volume* control(s) is **not** possible: not supported by the sequencers
- adding *instrument volume* control(s) seems achievable

So the difficult question is: *where* to add this(these) control(s)?
Here is a mock-up of what I currently have in mind, see bottom left of track table. Any feedback welcome.

![mock-up](https://github.com/helge17/tuxguitar/assets/129443524/bc830d85-f215-416d-acd1-52e0bd321738)


Note: it's a bit tricky to implement, feasibility is not yet demonstrated.

**Comment by sugizo** [comment]
human usually read from left to right, 
better to put the volume bar 
after instrument column, 
so that user can see 
what instrument they want to change it's volume, 

what do you think ?

if it's hard, for developer, 
then 
wherever place is good, 
as long as users have this feature

thanks and best regards

**Comment by guiv42** [comment]
That's the difficult part: control shall be separated from the tracks, since it *cannot* be associated to a single track. And the table can't be split in 2, to keep consistency of vertical scroll bar.

So I'll keep this layout. I currently target a simple behavior: show the volume control of instrument corresponding to selected line.
This area could be enriched in the future (and become kind of a simplified mixer?)

**Comment by sugizo** [comment]
**objective**
to simplified the process to adjust the volume

right now, 
if we want to adjust the instrument volume, 
we must double click the instrument 
then adjust it's value bar

like musescore and power tab example picture above

best regards

**Comment by guiv42** [comment]
> adding *track volume* control(s) is **not** possible

My mistake, finally it **is** :)
It could look like this:
![mock-up2](https://github.com/helge17/tuxguitar/assets/129443524/cbb9e4f0-c8c6-40f3-8c15-795f0219480f)

**Comment by sugizo** [comment]
great, thanks

another solution perhaps : 
put mixer out of the hidden place, 

the purpose is same 
to minimize user click just to adjust volume
another added value is 
user can change the instrument too (in case they want to taste different sound (muted, distortion guitar, etc)
like power tab and musescore

![image](https://github.com/helge17/tuxguitar/assets/2418295/ffedc77d-07bb-45af-959b-fe0ac042b319)

best regards

**Comment by guiv42** [comment]
> another solution perhaps : put mixer out of the hidden place

Note: there is already an option for that, just associate a keyboard shortcut to "Show Instruments" action (see menu Tools/Shortcuts)

Thanks for your feedback. Even if I'm still struggling with the user interface, I'm now quite confident I can get something working. The 2 options I mentioned above are still competing:
1. a dedicated "mixer area" on the left of track table
2. volume controls integrated *in* the track table

I don't know which one will look best at the end. The mock-up of option 2 above was done by "hijacking" a progress bar, to make it behave like an horizontal scale control (which definitely does not fit *inside* the table). It's a bit frustrating, as it looks really good in some configurations (e.g. Linux/SWT), but can be either ugly or buggy in others (e.g. Win10, or Linux/JFX).
Slowly progressing, this will take some time.

**Comment by sugizo** [comment]
**steps**
```
powershell -Command "Remove-Item C:\tuxguitar-*\ -Recurse"
cd %homepath%\Downloads
curl -LC - https://github.com/helge17/tuxguitar/releases/download/2023-12-22-snapshot/tuxguitar-2023-12-22-snapshot-windows-swt-x86_64.zip -o tuxguitar.zip
powershell -Command "Expand-Archive -LiteralPath %HOMEPATH%\Downloads\tuxguitar.zip -DestinationPath C:\tuxguitar"
powershell -Command "Copy-Item -Path 'C:\tuxguitar\*' -Destination 'C:\' -Recurse"
powershell -Command "Remove-Item C:\tuxguitar -Recurse"
powershell -Command "Remove-Item %HOMEPATH%\Downloads\tuxguitar.zip"
C:\tuxguitar-2023-12-22-snapshot-windows-swt-x86_64\tuxguitar.exe
```

**result**
brilliant, 
can adjust with mouse / touchpad and keyboard (left, right, down, up)

last question before closing issue : 
by chose option 1 above, 
so the volume control can't be put 
after the instrument name, 
isn't it 
?

thanks and best regards

**Comment by guiv42** [comment]
Thanks for the feedback, good to know you liked it.
As mentioned above, there is a real potential for improvement, this area could be enriched in the future.

> so the volume control can't be put after the instrument name, isn't it?

Instrument names are aligned with the cells representing measures on the right. Volume controls cannot be. And each zone has its own vertical scrollbar, so I confirm it's not possible.
