### ISSUE TITLE
Build problem on Linux

### ISSUE THREAD

**Issue by ycollet** [helge17/tuxguitar#148]
I am trying to build tuxguitar / master on Fedora 38 and I meet the following error message:
```
[DEBUG] Failed to resolve artifact: org.herac.tuxguitar:tuxguitar-pom:pom:1.6.0
[DEBUG] Resolving artifact org.herac.tuxguitar:tuxguitar-pom:pom:1.6.0 from [central (https://repo.maven.apache.org/maven2, default, releases)]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.herac.tuxguitar:tuxguitar-linux-swt-x86_64:1.6.0: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.herac.tuxguitar:tuxguitar-pom:pom:1.6.0 has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM @ line 2, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
```
The command line I used to build tuxguitar:
```
PATH=/usr/libexec/javapackages-bootstrap:$PATH /usr/bin/python3 /usr/share/java-utils/mvn_build.py --xmvn-javadoc -X -j -- -e -f build-scripts/tuxguitar-linux-swt-x86_64/pom.xml
```
This command line us used by the mvn_build macro from rpm / spec build.

**Comment by guiv42** [comment]
I don't understand the path you're trying to follow to build tuxguitar. Did you try with th ebuild instructions [install.md](https://github.com/helge17/tuxguitar/blob/master/TuxGuitar/doc/INSTALL.md) ?

**Comment by ycollet** [comment]
Sorry for the late answer. I followed the steps and it worked !

**Comment by guiv42** [comment]
good news :)
By the way, I don't know why you referred to "rpm spec" above. If you want to build a rpm package, one has already been built from this repo, see [here](https://build.opensuse.org/package/show/openSUSE:Factory/tuxguitar)
