### ISSUE TITLE
windows installerworks no more

### ISSUE THREAD

**Issue by blindfaced** [helge17/tuxguitar#149]
hi

i've just upgrade to win 11 pro 23h2 and i can't use the installer even in compatibility mode

thanks

**Comment by guiv42** [comment]
Which version of TuxGuitar?

**Comment by blindfaced** [comment]
the last one 03 11 2023 but in fact none, the installer doesn't launch no matter what i do

**Comment by blindfaced** [comment]
there is no error simply i can't use the installer

**Comment by guiv42** [comment]
can you try to launch it from a shell (e.g. powershell) to see if it is a bit more verbose?

**Comment by blindfaced** [comment]
i was prompt access denied

**Comment by blindfaced** [comment]
sorry i was in the wrong mode it works

**Comment by guiv42** [comment]
> sorry i was in the wrong mode it works

Sorry I don't understand this last comment. Shall I understand the installer works?

**Comment by blindfaced** [comment]
yes the installer works when launched from the shell with run as admin

**Comment by guiv42** [comment]
OK
I'm not very familiar with Win11... Is there a way to run the installer as admin without the shell? (like right-click on installer and "run as admin")
Anyway, it's somehow logical that admin privileges are required to install software.

**Comment by blindfaced** [comment]
I became lazy not to use a shell, thank you very much, I close as resolved

**Comment by sugizo** [comment]
tested work on command prompt without run as admin

```
cd %homepath%\Downloads
curl -LC - https://github.com/helge17/tuxguitar/releases/download/1.6.0/tuxguitar-1.6.0-windows-swt-x86_64-installer.exe -o tuxguitar.exe
tuxguitar.exe
```

the rest is press next, till finish 
then restart your machine

**Comment by blindfaced** [comment]
you're right but i'm not talking about that but : tuxguitar-snapshot-03-11-2023-windows-swt-x86_64-installer.exe
i mean i wanna know how tux guitar could be improved by any mean; 
i'm currently working with GP8 but i keep tabs on TG

**Comment by guiv42** [comment]
> I became lazy not to use a shell, thank you very much, I close as resolved

What's the status of this issue? Can it be closed?
