### ISSUE TITLE
How can I build tuxguitar for aarch64 ?

### ISSUE THREAD

**Issue by ycollet** [helge17/tuxguitar#157]
I tried to build tuxguitar for aarch64 but didn't succeed.
I dowloaded swt 4.21 for aarch64, but it looks like something is missing in the pom files.

**Comment by guiv42** [comment]
Hi
First, we decided not to support aarch64 in this repo, and to leave the arch adaptations to the different distros (see #137). At least for now (too many open topics currently). I guess that's what you're trying to do for Fedora, so thanks and good luck ;)
But unfortunately it means we do not work on this topic and we won't be able to provide much support.
I can just suggest to have a look at the rpm package of OpenSuse: maintainer did produce an aarch64 version. And yes this required some adaptation of the pom files. See [this patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/tuxguitar/0001-tuxguitar-aarch64.patch?expand=1)

**Comment by guiv42** [comment]
@ycollet : if this is OK for you, I suggest closing this issue (as mentioned above we won't be able to provide you much support here)

**Comment by ycollet** [comment]
Sorry, I forgot to close the ticket :) Done !
