### ISSUE TITLE
English language cannot be selected any more

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#16]
In menu Tools/Settings, "Language" tab, English has disappeared from the list of available languages
This issue has been introduced by 16cd950c5daf866f9ecc673b8393f57c7e1e5b46
It seems at least the messages_en.properties file in Tuxguitar/share/lang shall be kept. I do not know exactly about the 2 other files also deleted in this commit.
I clearly understand the concern to avoid duplicated files. Maybe another approach with relative path symlinks could be used instead?

**Comment by helge17** [comment]
Yes, sorry, 2caca79 should have fixed that.

**Comment by guiv42** [comment]
I'm sorry I did not see it!
My fork was a little behind... Got to synchronize
