### ISSUE TITLE
Very annoying bug that freeze the page but making the website work

### ISSUE THREAD

**Issue by thedoggaming16** [helge17/tuxguitar#167]
I don't know how to reproduce this but i film what happening. I was copying some drum path from an tabs to paste it to an another path and for no reason the app freeze. But i can interact with it even if the app if completely froze
and even when i tried to close the app, it bug... And i can't go away because the app is like in first plan (idk if your understand english is not my primary language I'm french speaker)

https://github.com/helge17/tuxguitar/assets/74026429/e7c0400e-b0a4-4f44-bbe2-bac700be02eb
https://github.com/helge17/tuxguitar/assets/74026429/57c02883-a3a6-475d-8678-8f2fa4fde08c

Thanks !

**Comment by thedoggaming16** [comment]
the first video seen to not work, there is the first video: https://www.youtube.com/watch?v=ZQFT5FPdo_w&ab_channel=Xx_Villager12_Xx

**Comment by guiv42** [comment]
Hi. Could you please precise which version of TuxGuitar?
Could you please try to find a way to reproduce the issue? Even better: if you can reproduce the issue after starting TuxGuitar from a console, so we can see if there are some logs.
If you cannot reproduce the issue I do not see any possible way to debug...

And feel free to switch to French language if English is a problem for you, I will understand ;)

**Comment by guiv42** [comment]
Sorry, switching to French for a while, trying to clarify.
@thedoggaming16 : besoin de plus d'information stp. Je vois bien qu'il y a un problème et qu'il est pénible. Mais comme il n'y a aucun message d'erreur, si on ne peut pas reproduire je ne peux tout simplement **rien** faire.
Peux-tu stp essayer de reproduire le problème, en lançant TuxGuitar depuis une console (ex: powershell). Au moins si ça plante on aura plus d'infos.
Si le problème n'est pas reproduit, mieux vaut fermer le ticket en l'état. Ca n'est pas la bonne volonté qui manque, mais là vraiment je n'ai aucun moyen d'avancer.

**Comment by thedoggaming16** [comment]
Comment je fais avec Powershell?

Et aussi je pense que c'est en ouvrant un projet déjà existant que l'appli se met en premier plan, ce qui empêchait d'ouvrir les autres apps (Même si je pouvait interagir avec ceux-ci comme à la fin j'ai réussi a écrire sur cette page même si je ne la voyait pas) Mais sinon je ne pense pas être capable ''d'intetionellement'' reproduire le bug. 

https://www.youtube.com/watch?v=V_6G97NPMfM&ab_channel=Xx_Villager12_Xx

**Comment by thedoggaming16** [comment]
ah et la version est celui du 2023-08-23 snapshot

**Comment by thedoggaming16** [comment]
je vias installer la version la plus récente. [2023-12-04-snapshot]

**Comment by guiv42** [comment]
> je vias installer la version la plus récente. [2023-12-04-snapshot]

Tu peux, mais ça ne changera rien.

Lance powershell depuis le menu démarrer windows. Si tu as utilisé l'installer pour installer TuxGuitar (exe), taper `tuxguitar` devrait suffire à le lancer. Sinon, si tu utilises la version standalone (zip), il faut naviguer là où tu as extrait le zip (tape la commande `cd "le chemin ou tu as extrait le zip`) puis tape `tuxguitar.bat`.
Au moins s'il y a un plantage ça laissera peut-être des messages d'erreur. Dans ce cas, copie-colle les messages et poste les ici.

Si tu n'arrives pas à reproduire le problème (d'un côté tant mieux...), de mon côté je n'ai aucun moyen de faire quoi que ce soit pour t'aider.

**Comment by thedoggaming16** [comment]
quand j'essaye de le lancer avec windows powershell (j'ai télécharger le tuxguitar-2023-12-04-snapshot-windows-jfx-x86_64-installer.exe) sa me dit

''tuxguitar : Le terme «tuxguitar» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou
programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès
est correct et réessayez.
Au caractère Ligne:1 : 1
+ tuxguitar
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (tuxguitar:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException''

**Comment by guiv42** [comment]
pfou, ça fait trop longtemps que je n'ai pas ouvert un windows, moi.
1. je conseille la version swt, et non pas la version jfx que tu as utilisée. Donc : xxxx-windows-**swt**-x86_64-installer.exe
2. Après avoir installé TuxGuitar, tu ouvres powershell tu tapes ça:
`& 'C:\Program Files\tuxguitar\tuxguitar.bat'`

A partir de là, si ça se plante, faire une copie du contenu de la fenêtre powershell et la poster ici.

**Comment by thedoggaming16** [comment]
Ok mais j'ai mis Tuxguitar sur un autre disque, comme je fais D:\tuxguitar\tuxguitar.exe sa marche et sa l'ouvre... mais D:\tuxguitar\tuxguitar.bat sa ne marche pas et sa dit ''Le chemin d’accès spécifié est introuvable.''

et si j'essaye d'ouvrir a partir de ton code, sa fait le même message d'erreur que tantôt

**Comment by guiv42** [comment]
Je peux te proposer deux possibilités :
1. tu utilises un installer (xxxx-windows-swt-x86_64-installer.exe), tu laisses TuxGuitar s'installer dans le dossier par défaut, et tu tapes la commande `& 'C:\Program Files\tuxguitar\tuxguitar.bat' ` dans powershell
2. sinon (plus simple) : tu télécharges une version zip (xxxx-windows-swt-x86_64.zip), tu extrais ce zip où tu veux, puis tu tapes la commande `& [chemin où tu as extrait l'archive]\tuxguitar.bat`.
Exemple, tu télécharges tuxguitar-2023-12-10-snapshot-windows-swt-x86_64.zip et tu l'extrais dans D:\tuxguitar, alors il faut taper `& 'D:\tuxguitar\tuxguitar-2023-12-10-snapshot-windows-swt-x86_64\tuxguitar.bat`

**Comment by guiv42** [comment]
@thedoggaming16 : any news ?
des nouvelles ? En l'état cette issue ne peut pas progresser (pas reproductible).

**Comment by thedoggaming16** [comment]
well actuallymy tuxguitar never crashed after i download these new versions. Thanks !

**Comment by guiv42** [comment]
closed: not reproduced
