### ISSUE TITLE
Musescore  warning when opening Tuxguitar generated MusicXML

### ISSUE THREAD

**Issue by BeFrankly** [helge17/tuxguitar#169]
When I use TuxGuitar menu entry "export as...MusicXML" the file generated will not open without warning in Musescore 3. Seems that Musescore parses the file and complains about not well formed XML. I.e.: the attached XML code generated by TuxGuitar brings the warning (here translated by me from an original german message): fatal error: row 10 column 34 The element creator is not defined in this area.

[Just_first_lines_exampleXML.txt](https://github.com/helge17/tuxguitar/files/13697601/Just_first_lines_exampleXML.txt)

First I can see, that the XML generated by TuxGuitar does neither contain a DTD nor XSD declaration so it is unclear, for me and for other software, which version of the MusicXML specification you are using. 

Musescore allows to open the file then, but you might want to to hear about this problem, so I post it here. Not a high score bug but for people using both, Tuxguitar and Musescore, it should be fixed some day.

This link might help: https://www.musicxml.com/for-developers/

Regards

Frank

**Comment by guiv42** [comment]
Just 2 questions:
- which version of TuxGuitar are you using? (Important question since there were recent modifications in musicXML export)
- Could you please join here the TuxGuitar file creating the problem? (so I can reproduce)

**Comment by BeFrankly** [comment]
@guiv42 , its TuxGuitar 2023-11-30-snapshot and I post here a short file just with some notes.
[AsleepBug.xml.txt](https://github.com/helge17/tuxguitar/files/13697755/AsleepBug.xml.txt)

**Comment by guiv42** [comment]
Just a very fast look at the commit history, it seems the musicXML export has been implemented quite a long time ago. So most probably an old version of MusicXML.

@BeFrankly : if you use musicXML format, I suggest to switch to a more recent version. Issue #37 was fixed after 2023-11-30 (erroneous octaves were exported to musicXML)

**Comment by BeFrankly** [comment]
Hello @guiv42 , I tested with the actual snapshot but still it doesn't work. I also tested with an older version of Musescore from 2019 and an actual AppImage of Musescore 4.2. The error message was always the same. So I did further tests with Musescore 4.2. I let Musescore generate some MusicXML output and did a diff between Tuxguitar and Musescore output. 

I also took a look on the musicxml.xsd (Stylesheet) of MusicXML version 4.0. So here ist what I found out:

The order of the tag generation done by Tuxguitar seem not to be ok. I.e. in the stylesheet, the tag "identification" is a complex type containing a sequence of elements. The "creator" element as well a the "encoding" belongs here. But in the stylesheet the element "creator" has to come before the element "encoding" has to come afterwards and not the way, Tuxguitar does. If you change the order of the elements maually, musescore does not complain about the "creator" element anymore. But then further down in the xml came other elements that are in the wrong order.

And as I told you: Your XML misses a DTD ore XML stylesheet link.

**Comment by guiv42** [comment]
> I tested with the actual snapshot but still it doesn't work

That was expected, but since the warnings do not prevent you to open the files, at least with this version you should have correct octaves displayed ;)

Considering there's no information in the code about the musicXML version used, and that this code is pretty old, I think the cleanest solution would probably be to completely re-write [musicXMLWriter](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java), ideally targeting musicXML 4.0.
I don't expect this to be very complex, but for sure time-consuming.
Then it's just a matter of priorities...

**Comment by guiv42** [comment]
It's fun... Did anyone *really* use the musicXml export option?

There is a confusion between **score** and **tablature** attributes: a standard tuned guitar track gets exported as a **score*** with 6 lines :D

see how it is displayed by MuseScore (just count the lines, a bit surprising!)
![Screenshot_20240227_234650](https://github.com/helge17/tuxguitar/assets/129443524/59215ccb-6147-485d-b55d-784a49fa88ee)

**Comment by guiv42** [comment]
That should be much better now. See the same chord as my previous post, exported in musicxml format and imported by MuseScore (with no warning raised):
![Screenshot_20240229_124437](https://github.com/helge17/tuxguitar/assets/129443524/0fdfd688-a01f-459e-9180-3ffbb961a6fe)

Only 5 lines in score, and 6 strings in tab :)
For the red notes, I'm not 200% sure but it looks it is a MuseScore problem. See this [issue](https://github.com/musescore/MuseScore/issues/21742) I created, it seems problem was not there in MuseScore 3.

@BeFrankly : can you please test if this is OK?

**Comment by profOnno** [comment]
I'm currently trying to read the musicxml in rust, and I've got a part working. I think i got past the Creator tag.

I think Musescore requires the tag. The [spec](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/identification/) says its optional (Zero or more times). So the export from tuxguitar is good.

To get it to import in Musescore, try to fill in the Composition properties (in tuxguitar). If I'm not mistaken it is the Author field... or just fill out all fields.

**Comment by guiv42** [comment]
@profOnno : I don't understand your comment
> To get it to import in Musescore, try to fill in the Composition properties

In fact I have no problem to import in MuseScore: after #257 the MusicXML files generated by TuxGuitar are correct. The problem is some notes are displayed in red, but I confirm it's a MuseScore issue. The instrument is not correctly selected, MuseScore selects a Cavaquinho instead of a guitar (see the issue I mentioned above)

**Comment by profOnno** [comment]
> @profOnno : I don't understand your comment

I probably misunderstood the problem.

**Comment by guiv42** [comment]
> I probably misunderstood the problem.

That's possible. I can explain this one easily: there is no problem any more ;)
From my point of view issue is fixed, I'm just waiting for the feedback of @BeFrankly to close it.

**Comment by BeFrankly** [comment]
Dear @guiv42 , sorry for my late reply to this. I'm a bit busy at the moment.
It's not clear to me, what you want me to do. Have you done a code change to fix this problem and I have to install a new Tuxguitar version first?

**Comment by guiv42** [comment]
No problem, nothing's urgent.

> Have you done a code change to fix this problem and I have to install a new Tuxguitar version first?

Yes. MusicXML export is progressing these days. It now export files compliant to musicXML 4.0, so the warning you have experienced should be solved now.
Could you please install the latest [snapshot](https://github.com/helge17/tuxguitar/releases), test it and close this issue if this is OK?

**Comment by BeFrankly** [comment]
@guiv42 , thanks a lot. Yes, this bug is fixed now and yes, there are a lot of red notes in Musescore. Thank you also for adding this as an issue there.

**Comment by guiv42** [comment]
About red notes in MuseScore, it's easy to fix: just edit song in MuseScore after import, and re-allocate guitar tracks to the correct instrument.
