### ISSUE TITLE
reselection of measures required when in loop mode

### ISSUE THREAD

**Issue by downToHell** [helge17/tuxguitar#173]
**Given**: I select a few measures (36-44) 
**When**: I enter loop mode
**Then**: The selected measures are to be found in the combo box as well

However if, I want to change the loop tempo (and do not explicitly keep the selection) it is always necessary to select the measures I want to have again as it pops back to the only measure (41 in the video) I selected. According to my understanding it shouldn't behave like that but rather keep the measures I selected previously (36-44).

https://github.com/helge17/tuxguitar/assets/36171067/28ef0200-6fe0-46fd-aa5b-00bb0bac7adc

**Comment by guiv42** [comment]
Hi.
I guess you are using 1.6.0?
Yes that's clearly a bug, already identified. It should have been fixed by eae6bb1d9285fe3a778fcaa402b9157332c36abc.
Could you please switch to a more recent [snapshot](https://github.com/helge17/tuxguitar/releases), and confirm it's ok?

**Comment by downToHell** [comment]
Yes, I am! Alright, once I've switched, I'll let you know
