### ISSUE TITLE
feature request: button for looping the current selection

### ISSUE THREAD

**Issue by downToHell** [helge17/tuxguitar#174]
As the new version of tuxguitar features selection now, it'd be quite cool to have a loop button to enter the play mode menu.

Appreciate your work!

Kind regards,
Thomas

![Toolbar](https://github.com/helge17/tuxguitar/assets/36171067/bf0f82d8-a4f1-4559-880a-040facb70080)

**Comment by guiv42** [comment]
@downToHell : could you please test latest [snapshot](https://github.com/helge17/tuxguitar/releases)?

**Comment by guiv42** [comment]
Done
![Screenshot_20240118_193200](https://github.com/helge17/tuxguitar/assets/129443524/4d5c119f-dad0-4118-ac16-6aeb0c30121a)
