### ISSUE TITLE
Error displayed by Android Studio

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#192]
Following 1229be76752fbde5f83442c8ab053bde4ce14d90

On [this line](https://github.com/helge17/tuxguitar/blob/464ea66d9db5c68f2f6ab457ea46e2a1521c741c/android/TuxGuitar-android/src/org/herac/tuxguitar/android/properties/TGResourcePropertiesReader.java#L43) Android Studio displays following error:
`Field requires API level 19 (current min is 16): java.nio.charset.StandardCharsets#UTF_8`

Anyway, I do not really understand, as it still builds...

**Comment by helge17** [comment]
I have not noticed this error in my build logs. If I understand correctly, this means that [1229be7](https://github.com/helge17/tuxguitar/commit/1229be76752fbde5f83442c8ab053bde4ce14d90) needs at least API level 19 to run TuxGuitar correctly. According to [this](https://developer.android.com/tools/releases/platforms) list, API level 19 is supported by Android 4.4 and later, API level 16 meant Android 4.1 and later. So updating minSdkVersion from 16 to 19 should avoid the error without any side effects.

**Comment by guiv42** [comment]
thanks!
