### ISSUE TITLE
utf-8 character not loaded correctly from tuxguitar.cfg

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#193]
With commit 1229be76752fbde5f83442c8ab053bde4ce14d90 I tried to enable utf-8 for config files and file history. utf-8 is now correctly saved to and loaded from file history (~/.config/tuxguitar/config/history.properties) and theme description skin.info files.

One problem remains: The config file tuxguitar.cfg is saved correctly with utf-8 characters, but when loaded again, the utf-8 characters are broken. I used the window.title entry in tuxguitar.cfg to test:

```
$ rm -r  ~/.config/tuxguitar/
```
Start TuxGuitar
Go to Tools -> Settings -> General -> Windows Title, enter some utf-8 characters, e.g. TEST öäüÖÄÜ
String is correctly shown in the windows title
Exit TuxGuitar
```
$ grep window.title ~/.config/tuxguitar/config/tuxguitar.cfg
window.title=TEST öäüÖÄÜ
```

Start TuxGuitar again
Windows title is broken
Exit TuxGuitar
```
$ grep window.title ~/.config/tuxguitar/config/tuxguitar.cfg
window.title=TEST Ã¶Ã¤Ã¼ÃÃÃ
```

**Comment by guiv42** [comment]
That should be OK now
@helge17 could you please confirm?
Note: your modification with 1229be76752fbde5f83442c8ab053bde4ce14d90 was perfectly relevant. It makes sure tuxguitar.cfg default file is read correctly if it contains utf-8 characters, and also it ensures the user-specific instance of this file is saved correctly.
Process to read user-specific config file is a bit different as it reads defaults first, then merges parameters with user-defined ones. So it does not follow the exact same path.

**Comment by helge17** [comment]
Thanks, it works perfectly now! And sorry for introducing bugs...

**Comment by guiv42** [comment]
No need to be sorry, and thanks for detecting it ;)
