### ISSUE TITLE
cannot build Qt5 version

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#20]
This post summarizes my attempt to build the Qt5 version of TuxGuitar (that I would like to patch).
There is a TODO file in build-scripts/tuxguitar-linux-qt5-x86_64/, stating that qtjambi should be [downloaded](https://github.com/tilialabs/qtjambi5) and built from source. Instructions given on this site about the procedure to build seem a bit confusing for me.
Furthermore, there are several versions of qtjambi out there. The one referred to by the TODO file seems a bit outdated (2017), and the latest release seems to be [there](https://github.com/OmixVisualization/qtjambi).
So I downloaded:
- the last available version of qtjambi for Qt5 from [here](https://github.com/OmixVisualization/qtjambi/releases/tag/v5.15)
- the last available version of qtjambi-native-linux-x64 for Qt5 from [here](https://repo1.maven.org/maven2/io/qtjambi/qtjambi-native-linux-x64/5.15.14/qtjambi-native-linux-x64-5.15.14.jar)

I installed both in maven environment following instructions from TODO file:
```
mvn install:install-file -Dfile=qtjambi-5.15.jar -DartifactId=qtjambi -Dpackaging=jar -DgroupId=org.qtjambi.qt -Dversion=5.15
mvn install:install-file -Dfile=qtjambi-native-linux-x64-5.15.14.jar -DgroupId=org.qtjambi.qt -DartifactId=qtjambi-native-linux64-gcc -Dversion=5.15 -Dpackaging=jar
```

I upgraded qtjambi version from 5.5.1 to 5.15 in the following pom files:
- build-scripts/tuxguitar-linux-qt5-x86_64/pom.xml
- TuxGuitar-ui-toolkit-qt5/pom.xml

And when I try to build tuxguitar-linux-qt5-x86_64, I get a lot of errors:
- "package xxx does not exist"
- "cannot find symbol: class xxx"

So it seems I have done something wrong when trying to set up qtjambi

note: I have not yet addressed the question to move to Qt6

**Comment by guiv42** [comment]
Update
I used versions 5.15.14 of [qtjambi](https://repo1.maven.org/maven2/io/qtjambi/qtjambi/5.15.14/qtjambi-5.15.14.jar) and [qtjambi-native-linux](https://repo1.maven.org/maven2/io/qtjambi/qtjambi-native-linux-x64/5.15.14/qtjambi-native-linux-x64-5.15.14.jar) and updated versions in pom files to 5.15.14. Then:
- replacement of "org.qtjambi.qt.xxx" by "io.qt.xxx" in all `import` statements in TuxGuitar-ui-toolkit-qt5 files solved almost all errors "package does not exist"
- manually importing [qtjambi-printsupport-5.15.14.jar](https://repo1.maven.org/maven2/io/qtjambi/qtjambi-printsupport/5.15.14/qtjambi-printsupport-5.15.14.jar) and [qtjambi-printsupport-native-linux-x64-5.15.14.jar](https://repo1.maven.org/maven2/io/qtjambi/qtjambi-printsupport-native-linux-x64/5.15.14/qtjambi-printsupport-native-linux-x64-5.15.14.jar) in maven environment + adding a dependency in pom file solved the last occurrence of this error

But, many errors remain (method does not exist, ...). Most probably incompatibilities between Qt versions 5.5.1 and 5.15.14.
Note: I could not find versions older than 5.15.14, possibly because of Qt6

**Comment by guiv42** [comment]
Hi
In fact I did not find so interesting to migrate to Qt5.15 (last Qt5 LTS) since it is already superseded by Qt6. So I spent some time to look at the Qt functions used by TuxGuitar and deprecated between Qt5.5.1 and Qt6.5.0. There are quite a few of them.
Most of them are relatively painless to bypass: enums renamed, arguments of functions changed type, function moved from one package to another, etc.
BUT... there are a few of them which I don't know how to handle:
- QApplication.invokeLater(Runnable r)
- QApplication.hasPendingEvents()
- QWidget.nativeId()

Especially the 2 first ones are really structural.
Just to have a try, I commented out the calls to deprecated functions (or replaced `invokeLater` by "run immediately"), at least to be able to build. I could build the app, but I get an unexpected error when I try to execute it:
```
java.lang.UnsatisfiedLinkError: /tmp/QtJambi6.5.0_30816/lib/libQtJambi.so.6.5.0: /usr/lib64/libQt6Core.so.6.5.0: version Qt_6_PRIVATE_API' not found (required by /tmp/QtJambi6.5.0_30816/lib/libQtJambi.so.6.5.0)
```
So I am a bit stuck here, and I don't know how to go any further. Anyway, not sure this should be a priority to solve this issue.

The question of the diversity of ui frameworks will have to be addressed one day: SWT + JFX + Qt = a significant amount of work to maintain all variants

**Comment by guiv42** [comment]
Hello @Auase
I'm sorry but I really don't understand how your comment is related to this issue.
My understanding is you are looking for an application handling Jianpu notation. Is that right? If so, then it's clearly not the right place to address this subject.
The issue mentioned here is purely technical, and only deals with compilation/execution of TuxGuitar in a Qt environment, and the associated Java/C++ binding (QtJambi).
Could you please move this comment to an independent [discussion](https://github.com/helge17/tuxguitar/discussions) dedicated to this topic? (or maybe I have misunderstood your comment?)

**Comment by guiv42** [comment]
Still progressing on this Qt issue. I think I have found alternatives to the deprecated features used by TG.
However, it still does not work, still with the same "version Qt_6_PRIVATE_API' not found" error.

But... my issue is clearly *not* linked to TuxGuitar!
Seems my environment is not set up correctly: I have the same error trying to run the "Hello World" example from [QtJambi doc](https://github.com/OmixVisualization/qtjambi/blob/master/www/How-to-develop-Qt-in-Java.md)

If someone succeeds to make this example run, I think I have a path towards a clean migration to Qt6

**Comment by Auase** [comment]
@guiv42 
Okay, sorry, my comment may not be appropriate here.
But I have a suggestion, which is to deal with the issue of http://www.tuxguitar.com.ar The link is because this domain name has already been registered by someone else.

**Comment by guiv42** [comment]
@Auase thanks for your update
I get your point about the website, but again this comment is relevant... but off-topic!
Could you please create another discussion about this website question? If it stays here in this Qt-related issue there is no chance anyone sees it

**Comment by guiv42** [comment]
Not much progress so far. Thanks to [QtJambi support](https://github.com/OmixVisualization/qtjambi/discussions/157) I could understand the reason why it does not work in my configuration: Qt libraries shipped by OpenSuse are not exactly the official ones. Don't know why.
I tried on fresh installs of Debian and Ubuntu: the version of Qt6 I could find with package managers is not the latest one. So still not compatible.
Does someone know how this compatibility with Qt was handled before? Did TuxGuitar ship Qt libraries?? (Not even sure Qt license would authorize that).
According to [todo file](https://github.com/helge17/tuxguitar/blob/master/build-scripts/tuxguitar-linux-qt5-x86_64/todo.txt) my understanding is that QtJambi was rebuilt from source by TuxGuitar. Well... it does not sound trivial. Not spent very much time on that activity, but there are too many dependencies I could not solve (despite installing gigabytes of packages)

**Comment by guiv42** [comment]
Much time spent on this activity, without success yet.
As time goes on, master branch has evolved significantly, and it will require more effort to update Qt variant. So, since no significant progress can be foreseen in a near future, Qt variant is abandoned (see #165)
Moved to "deprecated" folder by 75b6757ad436deb58512b456f514a7c9c2ca3472.
So, issue closed.

**Comment by RJVB** [comment]
Pity, but understandable.

Sadly I missed this entire endeavour; I'd have pointed out that the easiest way to build a variant with a Qt5 GUI would have been to build against Qt 5.5 (or whatever the later version is still API compatible). Qt guarantee that binaries built against an earlier Qt5.x will run against a newer 5.y runtime so the only effort would have been to built Qt 5.5 if Qt no longer provide binaries for that.
