### ISSUE TITLE
Support for fluidsynth.so.x.x in tuxguitar-1.6.x-linux-swt-x86_64 

### ISSUE THREAD

**Issue by eggmatters** [helge17/tuxguitar#207]
This is related to issue #120.
Running on Ubuntu 23.04 (Lunar)
## Behavior:
The fluidsynth plugin throws an error and its functionality is unavailable in this release (note this also is the same for the 1.5.6 version as well)
### Launch Tuxguitar
From `https://github.com/helge17/tuxguitar/releases/download/1.6.0/tuxguitar-1.6.0-linux-swt-x86_64.tar.gz` 
```
$ wget https://github.com/helge17/tuxguitar/releases/download/1.6.0/tuxguitar-1.6.0-linux-swt-x86_64.tar.gz
$ tar -zxf tuxguitar-1.6.0-linux-swt-x86_64.tar.gz
$ cd tar -zxf tuxguitar-1.6.0-linux-swt-x86_64
$ . tuxguitar.sh
```
Application launches with the following dialog:
![image](https://github.com/helge17/tuxguitar/assets/3791436/d7341efe-fea5-40f1-ae41-1273ec2e9663)
Exception is thrown:
```
(TuxGuitar:2247712): Gtk-WARNING **: 11:23:25.821: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
org.herac.tuxguitar.util.plugin.TGPluginException: /home/eggmatters/Tux/tuxguitar-1.6.0-linux-swt-x86_64/lib/libtuxguitar-fluidsynth-jni.so: libfluidsynth.so.2: cannot open shared object file: No such file or directory
	at org.herac.tuxguitar.player.plugin.TGMidiOutputPortProviderPlugin.connect(TGMidiOutputPortProviderPlugin.java:23)
. . .
Caused by: org.herac.tuxguitar.player.base.MidiPlayerException: /home/eggmatters/Tux/tuxguitar-1.6.0-linux-swt-x86_64/lib/libtuxguitar-fluidsynth-jni.so: libfluidsynth.so.2: cannot open shared object file: No such file or directory
	at org.herac.tuxguitar.player.impl.midiport.fluidsynth.MidiOutputPortProviderImpl.listPorts(MidiOutputPortProviderImpl.java:37)
. . .
(TuxGuitar:2247712): Gtk-CRITICAL **: 11:23:26.017: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
org.herac.tuxguitar.player.base.MidiPlayerException: Could not initialize class org.herac.tuxguitar.player.impl.midiport.fluidsynth.MidiSynth
. . .
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.herac.tuxguitar.player.impl.midiport.fluidsynth.MidiSynth
	at org.herac.tuxguitar.player.impl.midiport.fluidsynth.MidiOutputPortProviderImpl.getSynth(MidiOutputPortProviderImpl.java:54)
	at org.herac.tuxguitar.player.impl.midiport.fluidsynth.MidiOutputPortProviderImpl.listPorts(MidiOutputPortProviderImpl.java:32)
	... 17 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /home/eggmatters/Tux/tuxguitar-1.6.0-linux-swt-x86_64/lib/libtuxguitar-fluidsynth-jni.so: libfluidsynth.so.2: cannot open shared object file: No such file or directory [in thread "main"]
```
## Current workaround
Disable fluidsynth plugin: Tools -> Plugins -> fluidsynth (uncheck)
## (Likely) Root Cause
To install fluidsynth SO files:
```
$ sudo apt install fluidsynth
$ sudo apt install libfluidsynth-dev
```
Running again shows the same errors.
Fluidsynth libs exist but are likely either pathed incorrectly or are looking for an unsupported version:
```
$ find /usr -name 'libfluidsynth.so*'
./lib/x86_64-linux-gnu/libfluidsynth.so.3.1.4
./lib/x86_64-linux-gnu/libfluidsynth.so.3
./lib/x86_64-linux-gnu/libfluidsynth.so
```
I can investigate further but my work with shared objects is fairly limited. It seems like resolving the proper version would be an easy fix but, it might be tricky if there are breaking changes introduced in the 3.x libs.
(BTW) I don't know what the expected behavior should be as I don't know what fluidsynth does :smile:

**Comment by helge17** [comment]
There are two versions of fluidsynth: libfluidsynth2 and libfluidsynth3. TuxGuitar 1.6.0 was built against libfluidsynth2, which is no longer available in Ubuntu 23.04. Try to install the latest TuxGuitar snapshot. It was built against libfluidsynth3.

**Comment by eggmatters** [comment]
I just did that and came here to close the issue and saw your comment. My apologies for not attempting that prior to posting the issue. Please do let me know if you need any Ubuntu testing and/or debugging. I would be happy to help.

**Comment by guiv42** [comment]
> Please do let me know if you need any Ubuntu testing

Testing is *always* welcome! The simplest way to do that is to make sure you use the latest snapshot.

Just one stupid question: if you're working on Ubuntu, why do you use the .tar.gz version and not the .deb package?

**Comment by eggmatters** [comment]
Not a dumb question, and not a great answer. The maintained package is way behind (last I checked v1.3 or something) and had horrid sound support. I am a little leery of running `dpkg -i` on pretty much anything. Not so much security but just dependency hell. I had written an ubuntu-spcecific compilation patch for 1.4 about 4-5 years ago so I wanted to start with the `.tgz` and then compile from source. Your INSTALL.md worked perfectly.

**Comment by DanielGibson** [comment]
Note that you can run `dpkg -I` (or `--info`) first to show the dependencies etc

> TuxGuitar 1.6.0 was built against libfluidsynth2, which is no longer available in Ubuntu 23.04.

By the way, this is not just a problem with 23.04: 22.04LTS also only provides libfluidsynth3, and so does the current Debian stable ("Bookworm" from June 2023).

Might make sense to do a new stable release with libfluidsynth3 support, or if the current code is deemed to unstable for that (I don't know), provide .deb packages of 1.6.0 linked against libfluidsynth3.

Right now installing the current "stable release" of TuxGuitar is kinda frustrating - it starts, but I just couldn't get it to play any sound. I saw that the fluidsynth plugin needs an older version of the lib, but it wasn't obvious to me that the "TuxGuitar Synthesizer" or "Gervil" require libfluidsynth to work at all on Linux (at least unless you have hardware MIDI support, I guess; and Gervil still doesn't work for me and doesn't have any configuration to set a soundfont either - no idea if it even is a software synthesizer or just another way to talk to midi HW or whatever).

**Comment by eggmatters** [comment]
Debian is going to be a tough one unless you run it off of Sid which, isn't advisable just to get TuxGuitar working. Linux Midi is quite perplexing but I can assure you that Gervill and Fluidsynth are exclusive and both run strictly on ALSA. You may want to check your alsa settings with `alsamixer` I was able to follow the docs here to build latest with zero issues (:open_mouth: ) If it's not playing sound, start with ALSA. TBH, there's not that much difference that I could tell between the two. The nice feature to have would be loading soundfonts which I think is in play.

**Comment by DanielGibson** [comment]
In the current snapshot, I'm using the FluidSynth plugin, and in the plugin configuration I added soundfonts I had (by default it uses the included MagicSFver2.sf2, I added a few more), and in its "Audio" tab set Pulseaudio as output:

![image](https://github.com/helge17/tuxguitar/assets/1216493/0e6e8009-f7ba-41c5-9c85-62dc69faf8c9)


Then in the "Configure TuxGuitar" Sound settings I can select "TG Fluidsynth" with one of the soundfonts:
![image](https://github.com/helge17/tuxguitar/assets/1216493/6b03d26d-6630-40dc-a65e-eebfe9e7e9cc)

This gets me working sound, without configuring anything outside of Tuxguitar.

**Comment by guiv42** [comment]
> Might make sense to do a new stable release with libfluidsynth3 support

1.6.1 is on its way, beta1 is out ;)

**Comment by DanielGibson** [comment]
nice!
