### ISSUE TITLE
importing midi type 0 can lead to negative fret numbers

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#211]
tested on 1.6.0, Linux openSuse Tumbleweed.

Importing a type 0 midi file from archive present in [this post](https://github.com/helge17/tuxguitar/issues/205#issuecomment-1893981907) leads to negative fret numbers displayed.
This file contains several instruments in one single midi track. When TuxGuitar imports file, it merges all instruments notes into one single track. So, in the last beat, more than 6 simultaneous notes are present, with several instances of one single note. Most probably this situation creates the issue when TuxGuitar tries to find a string to play each note

**Comment by belfie13** [comment]
have a look at [CIID-Heaven.Hell-BibleBlackBass2.mid.txt](https://github.com/helge17/tuxguitar/files/13950044/CIID-Heaven.Hell-BibleBlackBass2.mid.txt) from issue #205 which has negative numbers (example at bar 26) and it is a type 1 midi file (should be, i can't verify that). also the notes used different channels on the one track in Logic Pro before exporting to midi, this could be an issue.

just fyi, the channels in logic can be used to determine which string the note should be played on (or tracks can be configured so the channels represent how high on the fretboard / the lowest position to play the note)

**Comment by guiv42** [comment]
> have a look at [CIID-Heaven.Hell-BibleBlackBass2.mid.txt](https://github.com/helge17/tuxguitar/files/13950044/CIID-Heaven.Hell-BibleBlackBass2.mid.txt) from issue https://github.com/helge17/tuxguitar/issues/205

I thing you mean #209, yes I need to have a look at that. It might be another problem though.
when I import CIID-Heaven.Hell-BibleBlackBass2.mid file with -12 transposition, and with latest snapshot, I cannot see any negative number. So my assumption currently is that #209 is more a problem of wrong tuning selection, to be confirmed when I find some time to analyze

**Comment by guiv42** [comment]
After a short analysis of the code, it seems problem can also occur with a type 1 midi, even without any tuning issue.
Distribution of notes to strings can be improved:
- it processes notes in one beat following order of midi events. It seems to me processing from lowest to highest should increase chances of success (globally less possible places on a fretboard for lowest notes)
- it seems it assumes all notes *can* be played, which can be false, if source midi file was not written for guitar. In some cases, unplayable notes *shall* be discarded

analysis still ongoing, but it seems it can be fixed.

**Comment by belfie13** [comment]
@guiv42 can you point me to where in the code this happens? I assume a few things but its overwhelming looking through all these files.

**Comment by guiv42** [comment]
Sure: just have a look at this commit: 0985b75fefc0c1bce89d4b6072299f34cdde27b4
Practically, when importing a midi track, measures/beats/notes are first created without any allocation of notes to strings. Once this is done, it loops on every beat and then [distributes notes to strings](https://github.com/helge17/tuxguitar/blob/64f92d6e09478af285beae655257b37bc8b85550/common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java#L891)

Take care, this fix is only related to how notes are distributed to strings **when importing a midi file**. So totally unrelated to "change tuning" action mentioned in #209.
