### ISSUE TITLE
feature request: select all

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#220]
can we get a select all function so we dont have to drag select each note to get the whole track

**Comment by guiv42** [comment]
it's already there, accessible with a shortcut (menu Tools/Shortcuts):
![Screenshot_20240121_124845](https://github.com/helge17/tuxguitar/assets/129443524/e6828537-4366-4979-8e68-12ef2ffc20bd)

**Comment by belfie13** [comment]
i really think that cmd+a by default should select all (select entire track) with an entry in the edit menu (as standard in other apps).

do you? if not i'm happy to close this

**Comment by guiv42** [comment]
OK, that could make sense to add a section in Edit menu with selection-related actions, and not only "select all".
At least it would show to users that these actions exist.

I'm personally OK with the reallocation of Ctrl+A shortcut, currently "action.beat.general.voice-auto".
I'll do that.
