### ISSUE TITLE
feature request: allow string shift on all selections

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#221]
if theres one note on the top string and you try and shift a selection up one string, the whole operation is aborted. just leave that note and shift the rest up.

if the purpose was to prevent users from breaking relative string position then i don't see this as beneficial in any case. if you want to keep relative string position of the notes, don't shift the notes of a selection that can't be shifted without breaking that.

why restrict the capabilities of the app? it makes a simple operation really hard to achieve with a work around. you have to select every note that can be shifted and then move on to the next block. sometimes only every second note so that's alot of select / shift up operations for the user to do.

**Comment by guiv42** [comment]
> if the purpose was to prevent users from breaking relative string position

Well, it was close to this.
When I extended all actions to be applicable on selected notes, I started from implementation of 2.0beta fork. But it proved to be a very simplistic implementation: loop on all notes and apply action. In many cases it proved inconsistent. Typically: "semitone up" shall be applied on whole chord or not at all.
So I applied this strategy globally when applying action to a selection: do it either for all notes, or for none at all. It appears that for some actions, applying partially could make sense... I'll have a look

**Comment by guiv42** [comment]
@belfie13 : this should be OK now, could you please test latest snapshot?

**Comment by belfie13** [comment]
yes i will test

> > why restrict the capabilities of the app?
> 
> It's a matter of point of view! Selection feature is quite recent (1.6.0), and "apply actions to selection" feature was also implemented quite recently. I consider this an extension of app, not a restriction :D

I meant the end product ;) good work!

**Comment by belfie13** [comment]
didn't work :(
![Screen Shot 2024-02-09 at 06 41 15](https://github.com/helge17/tuxguitar/assets/39270867/748b6815-fbd0-44a1-bb30-d60be2951634)
![Screen Shot 2024-02-09 at 06 42 31](https://github.com/helge17/tuxguitar/assets/39270867/50250918-7fbb-427a-95fa-1686fff4b26b)
![Screen Shot 2024-02-09 at 06 43 55](https://github.com/helge17/tuxguitar/assets/39270867/ac156db8-8954-4505-ba09-4c1c100f4640)
couldn't move this invalid selection up or down

**Comment by guiv42** [comment]
Hum... I don't understand. Did you use latest snapshot?
Here is what I get, using shift+up/down keys (with 2024-02-06)

https://github.com/helge17/tuxguitar/assets/129443524/e28ad1b9-4ba2-4358-8d55-628be7761451
