### ISSUE TITLE
JDK version used

### ISSUE THREAD

**Issue by SimplyTheOther** [helge17/tuxguitar#229]
The [`INSTALL.md`](https://github.com/helge17/tuxguitar/blob/master/INSTALL.md) file mentions JDK 7 or higher is required, but the code uses Java 8 features such as streams and lambdas (e.g. `TGChangeAccentuatedNoteAction`) and Java 9 features like diamond operator inferred generics (e.g. `new ArrayList<>()` in `TGStoredBeatList`).

As such, what is the intended minimum supported JDK version? It would be nice to have Java 10 features such as local variable type inference, for instance, if supporting Java 10 wasn't an issue.

**Comment by guiv42** [comment]
thanks for pointing this out
Here is the rationale:
Most probably, info in install.md was correct when this repo was initiated.
The 2 examples you mentioned are portions of code I have back-ported from [another fork](https://github.com/helge17/tuxguitar-2.0beta). There, doc was not updated either: it also refers to JDK7.
I have done only small modifications in that code (essentially bug fixes), and so I did not inspect it in details. And I'm not a java developer, just an amateur, so I did not notice this JDK version evolution.

So, what shall we do now? I don't know.
We could adapt the code to restore compatibility with jdk7 (I should be able to identify easily the commits where code was imported from 2.0beta).
Or we could upgrade the minimum supported version. But I have to admit I don't know the consequences.

Help would be appreciated!

**Comment by helge17** [comment]
Currently I am building TuxGuitar

- on Debian 12 for Linux & Windows: OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1deb12u1, mixed mode, sharing) - up-to-date packages in Debian 12
- on Debian 12 for Android: OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Debian-1deb11u1, mixed mode, sharing) - packages from Debian 11; did not work with OpenJDK 17
- on MacOS 11 x86 for MacOS: OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)
- on FreeBSD 13.2 for FreeBSD: OpenJDK 64-Bit Server VM (build 11.0.20+8-1, mixed mode)

So I would suggest to update the minimum version info in INSTALL.md to JDK 9, or even up to 11, if you prefer.

**Comment by guiv42** [comment]
@SimplyTheOther : can we close this issue now?
