### ISSUE TITLE
Feature Request: IDE Agnostic Build Instructions

### ISSUE THREAD

**Issue by Vendelisk** [helge17/tuxguitar#246]
The current instructions only support developers using Eclipse, which covers [~30%](https://www.jrebel.com/blog/best-java-ide) of potential contributors.

It seems worthwhile to add a few more paragraphs explaining what the appropriate Maven project is / a general lifecycle usage guide / the location of the final .jar after packaging / etc.  Really, anything that Eclipse handles behind the scenes that isn't obvious outside of it.

This is probably low priority but might help more people get involved and add some much needed visibility to the repo.

**Comment by guiv42** [comment]
Hi. I'm not sure I completely understand your request, anyway let me try to provide a few answers: anything which can ease the job of potential contributors is for sure welcome!

> The current instructions only support developers using Eclipse

Did you have a look at [install.md](https://github.com/helge17/tuxguitar/blob/master/INSTALL.md)? This doc details how to build without the need to use any IDE.

> It seems worthwhile to add a few more paragraphs explaining what the appropriate Maven project is / a general lifecycle usage guide / the location of the final .jar after packaging / etc

Desktop app is available in several flavors:
- OS: linux (tgz), linux (deb), windows (standalone), windows (installer), macOs, freeBsd
- ui framework: SWT, JavaFX. Yet only the SWT variant is included in official delivered versions.

One Maven project is available for each couple [operating system / ui framework]. All are located in [build-scripts folder](https://github.com/helge17/tuxguitar/tree/master/desktop/build-scripts). The pom file for each project defines where .jar files are copied after app is built (see [example for linux/swt](https://github.com/helge17/tuxguitar/blob/7f559ad5a381e777f3223595af990e9437c60d52/desktop/build-scripts/tuxguitar-linux-swt-x86_64/pom.xml#L334)

> anything that Eclipse handles behind the scenes that isn't obvious outside of it

I don't think Eclipse handles so much behind the scenes, everything is properly specified by the pom files

**Comment by Vendelisk** [comment]
Hey, thanks for the links!

You're right that there is enough information to be able to figure it out
on your own if you're dedicated enough.

I wasn't so much suggesting that it's not possible to use another IDE, just
that the contribute.md
<https://github.com/helge17/tuxguitar/blob/master/doc/contribute.md> be
updated to make it more straightforward.
It took me 4 or 5 hours of digging around pom files and other code
fragments to figure out how to get my changes to show up in a build and run
on Debian.

Granted, I haven't used Java since college and I missed the install.md
<https://github.com/helge17/tuxguitar/blob/master/INSTALL.md> (which
would've helped) so I probably took longer than the average potential
contributor but I would bet there are a non-zero number of people who are
stopped by this.

**Comment by guiv42** [comment]
> It took me 4 or 5 hours of digging around

I can understand, I've gone through this also ;)

> I would bet there are a non-zero number of people who are stopped by this

install.md and contribute.md were written to limit this effort, but I agree some improvement is still possible.
Suggestions, to improve contribute.md:
- add the info about maven projects (see my post above)
- add a link to install.md before the Eclipse-specific section

I can update the doc with this info. Any other idea for improvement?

**Comment by Vendelisk** [comment]
That should help, thanks!

That's all I can think of now but I'll keep an eye out for more improvements.

**Comment by guiv42** [comment]
OK I'll do that when I find some time, thanks for your feedback.
Don't hesitate to ask for support if you need, this code is quite wide and not documented. It's been several months now I've been digging in it, so I might be able to guide you if you look for something in particular (though I can't promise!)
