### ISSUE TITLE
Using JTable for a Plugin on MacOS (Apple M1 Chip)

### ISSUE THREAD

**Issue by L4m4L** [helge17/tuxguitar#252]
Hi all, 

Firstly, thanks for keeping this project alive! Appreciate the effort put into the development/maintaining of TuxGuitar. 

I have a plugin that I would like to port over to MacOS, using this version of TuxGuitar. This plugin uses javax.swing to create GUI elements, but my plugin is crashing when creating a JTable. I think this has something to do with the fact this is a x86_64 app, but the Mac I am trying to run it on is using a M1 chip? 

The error that appears is `java.lang.UnsatisfiedLinkError` with libfontmanager.dylib. This library is unable to load `/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib`

If I create a symlink to the local version of libharfbuzz I have on my system, another error appears `Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (mach-o file, but is an incompatible architecture (have 'amd64', need 'x86_64)` 

So my question is - is it possible for me to get javax.swing working on this installation? It is odd because the TuxGuitar app itself works perfectly, so I assume that the architecture I am running is okay?

Would appreciate any help/thoughts. 

Cheers

**Comment by guiv42** [comment]
Hi
How is your plugin built?

**Comment by L4m4L** [comment]
Hello, 

Thanks for your response. 

I am currently using Eclipse/Maven to build my plugin, with tuxguitar-1.5.6.jar, tuxguitar-editor-utils-1.5.6.jar and tuxguitar-lib-1.5.6.jar as dependencies. This is because I was previously building for the version maintained on Sourceforge, and I don't think this should introduce any issues.

The plugin is being built on a MacBook Air running Ventura 13.1 with an Apple M1 chip. 

Does this answer your question?

**Comment by guiv42** [comment]
I was just wondering how you handle the dependency to javax.swing, since your 1st post pointed to that direction.
Sorry if my question is stupid: did you rebuild the plugin vs. version 1.6.1 of TuxGuitar jar files?

**Comment by L4m4L** [comment]
No your question is fine, just hoping I answered it! I just import
javax.swing.JTable, JFrame etc at the top of my java file. I have rebuilt
the plugin using TuxGuitar v1.6 (TuxGuitar, TuxGuitar-lib and
TuxGuitar-editor-utils) and it is still not able to create javax.swing
elements

**Comment by L4m4L** [comment]
Hello,

I tested the Standard Widget Toolkit library last night, and that appears
to work - so I will push forwards with this and see how I go!

Cheers

**Comment by guiv42** [comment]
@L4m4L: can this issue be closed?
