### ISSUE TITLE
rationalize definition of tuning presets

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#269]
note: this issue is precisely documented with the intention to make it accessible to a newcomer.

# description of issue
A list of 5 tuning presets is hard-coded in [MidiSongReader](https://github.com/helge17/tuxguitar/blob/169a5e14371584cacc75fcc9d093152af2bf916c/common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java#L699): it is used to select an appropriate tuning preset when importing a midi file. This list has been there for a while.

More [recently](https://github.com/helge17/tuxguitar/commit/ae3a36bd4d828a9f3ae7fda5ea75f8e4ca5dea2e), a configurable list of tuning presets was added in the form of a [tunings.xml](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar/share/tunings/tunings.xml) file. So now, some identical tuning presets are coded at 2 different places.

Objective is to cleanup code: remove duplicated definitions to ease future maintenance.
In a first step, actual behavior should remain unchanged. Then, tuning preset selection when importing midi files could be improved just by editing the xml.

# how to fix
Proposal: make the priority of tuning presets configurable in xml file. This is the way I would implement it:
- add an optional attribute `priority` to tuning presets in tuning.xml file. Define value 1 for standard E-tuning, 2 for Dropped-D, etc, to reproduce priorities currently hard-coded  in MidiSongReader.
- Add an integer attribute `priority` in [TGTuning](https://github.com/helge17/tuxguitar/blob/master/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTuning.java) class, with value imported from xml file content (and a default value if no attribute in xml). Import of tuning attributes from xml is done in [TuningReader](https://github.com/helge17/tuxguitar/blob/169a5e14371584cacc75fcc9d093152af2bf916c/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/xml/TuningReader.java#L58)
- implement `Comparable<TGTuning>` interface in `TGTuning` class, so  instances can be sorted by `priority` order (instances with no priority attribute should come last)
- in [TuningManager](https://github.com/helge17/tuxguitar/blob/master/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java), add a method `getPrioritizedTgTunings`, which returns all TG tuning presets with a defined `priority` attribute, sorted by its value (refer to [`getTgTunings`](https://github.com/helge17/tuxguitar/blob/169a5e14371584cacc75fcc9d093152af2bf916c/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java#L56)). Discard tuning presets with no priority.
- in MidiSongReader (`TrackTuningHelper.getStrings`), delete `if () else if()` sequence over successive hard-coded presets. Retrieve list of presets sorted by priority from TuningManager. Then, loop over this list until an acceptable tuning preset is found (min/max criterion unchanged)
- if none is found, keep actual strategy to create ad hoc tuning ([the last `else` condition](https://github.com/helge17/tuxguitar/blob/169a5e14371584cacc75fcc9d093152af2bf916c/common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java#L739))

# how to test
See attached files below.
[testTuning.zip](https://github.com/helge17/tuxguitar/files/14547370/testTuning.zip)

With menu "File/Import/Import Midi", import midi file from archive (transpose 0). Result should be identical to the .tg file also included in the archive. Each track corresponds to one current `if` case (5 hard-coded tuning presets + the last `else` condition). When writing this issue this test currently passes (169a5e14371584cacc75fcc9d093152af2bf916c).

Note: that would be **much** better if this test could be directly implemented in the code base, instead of keeping it manual!

**Comment by tdan** [comment]
Thanks @guiv42 for the detail steps. I'm working on this issue now :)

**Comment by guiv42** [comment]
Just for information, another place where "default tunings" are defined:
https://github.com/helge17/tuxguitar/blob/6e5bd2adb15cfa6111bff75dcd6d7dc7ed8125ca/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGSongManager.java#L25

**Comment by tdan** [comment]
> Just for information, another place where "default tunings" are defined:
> 
> https://github.com/helge17/tuxguitar/blob/6e5bd2adb15cfa6111bff75dcd6d7dc7ed8125ca/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGSongManager.java#L25

I got the first part down, ready to merge, but not sure how I should go about this part. Should "Default Tunings" be Prioritized Tunnings List from the xml file?

**Comment by guiv42** [comment]
Let's do it step by step, especially for a first contribution.
So, if you have something ready, just create a pull request now.

It would be better if we can remove all duplicated data, but this can be done afterwards.

**Comment by tdan** [comment]
I'll be happy to take a look :)
---
*Trung An*
Software Developer, Fifty8 Co. <http://fifty8.co>
916-420-3883

**Comment by tdan** [comment]
Hi @guiv42,

The hard-coded presets are the default tunings assigned whenever you add a new track to a song.

We can reuse the tunings defined in the XML file by leverage `TuningManager`. We'll use it to retrieve `priorityTgTunings()`. Then, in the `createStrings()` method, we'll find the highest priority tuning (lowest numerical value) that is associated with the number of strings requested.

The challenge lies in obtaining a `TGContext` object. Currently, the only approach I can see involves retrieving a `TuxGuitar` instance and extracting the context from it. Here's an example of how it might look:

	public List<TGString> createDefaultInstrumentStrings(int stringCount) {
		TuxGuitar tgInstance = TuxGuitar.getInstance();
		TuningManager tuningManager = TuningManager.getInstance(tgInstance.getContext());
		
		List<TGTuning> defaultTunings = tuningManager.getPriorityTgTunings();
		
		return createStrings(stringCount, defaultTunings);
	}

However, this approach requires adding `org.herac.tuxguitar` to `tuxguitar-lib` as dependency. I'm not sure if this is the most suitable solution, given my limited experience.

**Comment by guiv42** [comment]
Thanks for your clear analysis.

> this approach requires adding org.herac.tuxguitar to tuxguitar-lib as dependency

You cannot do that, for 2 reasons:
- there is already a dependency from tuxguitar to tuxguitar-lib, so that would create a circular dependency
- you shall not include any dependency from any module in [common](https://github.com/helge17/tuxguitar/tree/master/common) folder to a module out of this folder. All modules in "common" folder are used by both desktop and android apps, so for example adding a dependency to a module in "desktop" folder would break Android app.

So I suggest leaving TGSongManager unchanged, I think it's not worth a deep rework.

However this made me realize that we have a problem in the Android app, where the [tuning.xml](https://github.com/helge17/tuxguitar/blob/master/android/TuxGuitar-android-resources/resources/tunings/tunings.xml) file was duplicated. Now it's missing the `priority` attribute. This problem illustrates the risk of data duplication: inconsistency.
Logically PR #319 should have broken the "midi import" feature of Android app. Practically it seems it did not, because feature was already broken before! (don't know why).

So, I propose to
1. close this issue
2. replace `tuning.xml` file in Android resources by a symlink to `tuning.xml` file of the desktop app
3. create a new issue for "midi file import" feature in Android app

If that is OK for you, just close this issue I can take care of 2. and 3.

**Comment by guiv42** [comment]
Action 2. has been done (#371).
Interesting info: this action has shown that previous fixes implemented in "tuning.xml" file for desktop app were forgotten in Android app.
So, this issue is perfectly relevant: avoid duplicating data!

By the way, #371 also extends #319 to Android, so midi import now works correctly.

@tdan I think this issue can be closed, it's up to you

**Comment by tdan** [comment]
Sounds good to me. I'm glad the both desktop and Android version are
working correctly with the tuning.xml file

I'll start working on #289 like I mentioned in that thread, unless you want
me to take care of something else.

**Comment by guiv42** [comment]
OK, so I close this issue.
(and you can work on whatever you want)
