### ISSUE TITLE
MusicXML export missing the barline and repeat tags.

### ISSUE THREAD

**Issue by profOnno** [helge17/tuxguitar#271]
Hi,

The MusicXML export is missing the `barline` and `repeat` tags.

I was trying to add it but haven't coded in java for a long time. I'm willing to work on it.
I've got the code from github and did the INSTALL.md. The compile with mvn worked..

When i add a comment in the code (using nvim) i'll get an compile error. 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project tuxguitar-musicxml: Compilation failure
```[ERROR] /home/teknomen/java/tuxguitar/desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java:[98,107] package TGVersion does not exist```

So I'm guessing, Eclipse does some magic? and the TGVersion is generated?

Cheerz,

Menno

**Comment by guiv42** [comment]
Barlines and repeat tags should be quite easy to export I guess:
- TuxGuitar `TGMeasure.getHeader().isRepeatOpen()` seems consistent with musicXML `<measure><barline><repeat direction="forward">`
- `TGMeasure.getHeader().getRepeatClose()`: see `<measure><barline><repeat direction="backward" times=`
- `TGMeasure.getHeader().getRepeatAlternative()`: see `<measure><barline><ending>`
- end of song (double bar): see `<measure><barline><bar-style>light-heavy`

> So I'm guessing, Eclipse does some magic? and the TGVersion is generated?

No... I don't understand this

**Comment by profOnno** [comment]
Already got the code... hard part is the compile part. Git clone without eclipse console `mvn clean verify` works when i won't change the code..

The I tried eclipse, got some setup issues... Imported the run configs, but got an error `can't find base` at the run configuration... selected it using file... then something worked. Compiled my changes, no problem. Trying to run it, using `tuxguitar.sh` in the `target/tuxguitar-SNAPSHOT-linux-swt-x86_64` folder, nothing happens... no error, no launch. Gonna get some sleep and try to again tomorrow.

**Comment by guiv42** [comment]
That's weird. Once again I confirm: you do no need to setup Eclipse. I started contributing to TuxGuitar about a year ago, just with a standard text editor and a console. For simple modifications (e.g. localized in one single file like what you are doing) that can clearly be sufficient.
If `mvn clean verify` works on the cloned source, I do not really understand why it would not work after editing MusicXMLWriter.java. Especially with such an error message about TGVersion!
Don't hesitate to push your modifications into a dedicated branch of your repo, so I can have a look at it (and try to build it).

**Comment by guiv42** [comment]
> I've got a small problem with the run configuration. If I use the run configuration from eclipse, tuxguitar starts without the plugins?

Yes, unfortunately that's a [known limitation ](https://github.com/helge17/tuxguitar/blob/169a5e14371584cacc75fcc9d093152af2bf916c/doc/contribute.md?plain=1#L104) of the procedure to setup Eclipse environment. Especially annoying for debug. I didn't have time to investigate this. If you can find a solution please don't hesitate to update procedure in [contribute.md](https://github.com/helge17/tuxguitar/blob/master/doc/contribute.md)

**Comment by profOnno** [comment]
I'll keep it in mind, waiting for a eureka moment :p. I is not on my priority list at the moment.
But I do have some code pushed to my clone of `tuxguitar` in a different branch, I'll wait with a merge request until a got some other enhancements added, like lyrics and maybe `coda`.

**Comment by guiv42** [comment]
> I do have some code pushed to my clone of tuxguitar in a different branch

Good news, thanks !

> I'll wait with a merge request until a got some other enhancements added, like lyrics and maybe coda

In this case, I would recommend to follow [github best practices for pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs): write small PRs.
So I would prefer if you create a PR now, and complete the job later. Smaller PRs would make code review easier for me :)

Another thing: could you please squash your commits before sending a PR? (still to simplify code review). One possible pattern to handle this case is to work with 3 local branches. That's what I do personally:
- my master branch just follows this one in this repo (I only pull in this branch)
- I work in a local dev branch, with possibly many small successive commits
- when I'm finished, I merge-squash into a feature branch, then I push this feature branch to github to create a PR

**Comment by guiv42** [comment]
hi @profOnno 
I've assigned this issue to you, since you've done most of the job already (thanks for #275!).
So it's up to you now if you want to close this issue, or to go further with alt repeat (and end of song bar?).

(in other words: I don't plan to work on this personally)

**Comment by profOnno** [comment]
We can close this one. And open another one, or wait to open an other one, till there is someone (me?) who wants to work on it.
I'm going for the lyrics (without the rest notes), and I also need to spend some time on actually learning to play guitar :grin:
