### ISSUE TITLE
Run and Debug configuration Eclipse

### ISSUE THREAD

**Issue by profOnno** [helge17/tuxguitar#273]
There is/was a problem with with enabling debug for plugins in eclipse.

I got a solution for the plugin I'm working on `tuxguitar-musicxml`. 

In `run configurations`, in the `arguments` tab change the working directory to other `${workspace_loc}/tuxguitar/desktop/build-scripts/tuxguitar-linux-swt-x86_64/target/tuxguitar-SNAPSHOT-linux-swt-x86_64`. This should make the run button to work.

To get debug working I had to add 2 jars to the `dependencies` tab. So select `Classpath Entries` click `Add Jars...`.
Then select `tuxguitar-gm-settings/target/tuxguitar-gm-settings-SNAPSHOT.jar`. Do the same for `tuxguitar-gm-utils-SNAPSHOT.jar`

I've got an updated run configuration in my fork b2bbe475a018c9c949e2e3d84acce022808d8e4a
This worked for me.

Cheers,

Menno

**Comment by guiv42** [comment]
> I've got an updated run configuration in my fork

Good news, thanks!
Do you think you can create a dedicated Pull Request to update [development configs](https://github.com/helge17/tuxguitar/tree/master/development) and [contribute.md](https://github.com/helge17/tuxguitar/blob/master/doc/contribute.md)?
