### ISSUE TITLE
MacOS SWT version used is 4.13 from 2019 and may be upgraded

### ISSUE THREAD

**Issue by G-eos** [helge17/tuxguitar#292]
Cocoa version used seems to be 4.13 as defined in install.md: https://archive.eclipse.org/eclipse/downloads/drops4/R-4.13-201909161045/swt-4.13-cocoa-macosx-x86_64.zip
This version is from 2019. I have no idea of the difficulty to update, probably today OS version is better supported.

This is probably a o-long term enhancement.

**Comment by G-eos** [comment]
Moreover, https://github.com/helge17/tuxguitar/blob/master/doc/contribute.md explain to use a newer version than Install.md :)

**Comment by guiv42** [comment]
I guess you are talking about SWT ?

**Comment by G-eos** [comment]
You have probably right, SWT.
I follow install.md which defined to download and install swt-4.13-cocoa ... and contribute.md another version (which I see after opening this issue).

As there is discussion on SWT, I propose to close this issue. Or to keep it to track that at least two .md files point to different version, up to you.

**Comment by guiv42** [comment]
It's fully possible that different versions of SWT are referred to at different places. Typically, it is not possible now to use the same version on all platforms (freeBSD uses another one).

"contribute.md" explicitly describes how to setup Eclipse environment to build the **Linux** version. So I think documentation is consistent.

That being said, your proposal to update to a newer version in macOS context could make sense, I don't know.
Take care that using the most recent version may not always be the best solution (e.g. Linux openSUSE currently ships SWT version 4.15, see #288)

**Comment by helge17** [comment]
See discussion #250, especially under "Cocoa integration plugin": If we could remove (or fix?) this plugin, I would update SWT to 21 (as on Linux and FreeBSD).

Help with MacOS would be much appreciated in general ;-)

**Comment by G-eos** [comment]
I think we can close this one. Work is in progress in [355](https://github.com/helge17/tuxguitar/issues/355)

(tiyle renamed to SWT and not Cocoa)
