### ISSUE TITLE
Won't open on M1 Macbook Air Monterey at all

### ISSUE THREAD

**Issue by Sy256** [helge17/tuxguitar#30]
I am on M1 Macbook Air Monterey. The official tuxguitar version macosx-cocoa-64 1.5.6 opens but none of your releases do I tried each one, for macosx-swt-cocoa-x86-64. It unzips at around 89mb (the official that works is 282mb), looks like the icon of the app, and then the first time I open it I get the message 'do you want to open this application unknown develop etc etc' and say yes and then just keep clicking it and nothing opens.

This is the only relevant picture but keep in mind this is normal and happens with every downloaded app the first time. Usually they open afterwards though.

<img width="266" alt="Screen Shot 2023-05-08 at 11 20 09 AM" src="https://user-images.githubusercontent.com/37394138/236901609-18f6eb13-92d4-4adb-b510-3aa6f6b77245.png">

So I click open on this, the message goes away, and nothing happens. I try opening it again, no message this time, nothing happens. Nothing loading in the background AFAIK

**Comment by helge17** [comment]
Version 1.5.6 for macOS contains a Java JRE, my macOS package does not. Probably this is the reason why it does not run on your machine.

Try to install OpenJDK from https://jdk.java.net/, then the package should work.

I will try to add OpenJDK to my package with the next release.

**Comment by Sy256** [comment]
Ok thanks I'll try that. I downloaded JDK 20...I'm not sure which one I need because there dont seem to be system requirements but that's the newest one. 

Another thing I'm finding is once I try to open yours and it fails, the original one doesn't open anymore either, until I restart the whole computer. That might also be associated with trying to build the tuxguitar 2.0 beta I linked to you earlier though

**Comment by Sy256** [comment]
Ok I unzipped JDK 20 it is just a folder, what am I supposed to do with it?

**Comment by Sy256** [comment]
Ok I figured out find a commercial build instead and installed JDK 20 for ARM64 with a dmg file from here https://www.oracle.com/java/technologies/downloads/#jdk20-mac

But same thing happens with your tuxguitar.

**Comment by helge17** [comment]
The latest release comes with OpenJDK, please try it.

**Comment by Sy256** [comment]
Hey! Sorry I just tried it now but I can't get it working...it OPENS and it shows in the About section that it IS 05-17-2023 snapshot, but none of the new features seem to be there and it works the same way as 1.5.6 did. So in other news after a nightmare of days of tinkering from the help of a reddit friend I was able to open 2.0 which has copy pasting available so I'm fine using that if this can't work for me. It came with the tradeoff of the default sounds not working though, I have to route it through a DAW to get any sound but thats fine for my purposes. Thanks for trying

**Comment by helge17** [comment]
Thanks for your feedback! Good to hear that the current builds can be opened on M1 Macs as well.

Currently the 1.x version looks pretty much the same as 1.5.6, that's true. We are trying to provide stable builds for all platforms, clean up and carefully add new features without breaking compatibility with 1.5.6.

Currently guiv42 is working on copy/paste and as soon as it is ready I will provide new binaries here, so stay tuned!

**Comment by Sy256** [comment]
Oh, great! Ok so it did open correctly its just it doesnt have the new features/menus yet, I thought it did because of that video on the front page. Got it, thanks I'll stay tuned!

So just to be clear is 2.0 a past project thats now not being updated, and you and guiv42 and are working on branching ("forking"?) off from that team? Or are they 2 entirely different branches?

I have another feature request but this one's probably much more involved and I get if you guys can't do it. We have click and drag to select in 2.0, but could there be a way to click and select only certain notes of the selection? Like the top string only or something? Maybe hold a modifier key while dragging to box select one string? I would mostly use it for drum transposing.

**Comment by guiv42** [comment]
These are different branches. The "2.0b" has forked from SourceForge several years ago, and is no more active. A major problem is it has followed for some time a parallel path, and is inconsistent (and incompatible) with the last 1.5.6 official release. What we are trying to do is to restart from the last published version of source code from SourceForge to have a clean and linear history, and to keep compatibility while integrating new features carefully.

Selecting only a few notes within 1 beat seems really complex, I don't think I will be able to do that. Just an example: contiguous notes in the tab are not necessary contiguous in the score, so how to handle vertical mouse drag? So I think I'll try to address other improvements first, there is a lot to do!
