### ISSUE TITLE
impossible to add new parameters in tuxguitar.cfg file in the future

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#31]
This is a side effect of commit f5fafce1e8b591f898e3c73f1b983857d555e7c9

Since the folder name for user configuration doesn't contain TuxGuitar's version any more, new versions SHALL be able to load config files created by old versions. Or it will never be possible to add new config parameters in the future.
Currently this situation is not correctly handled.
While working on a new feature, I tried to add a new parameter. When starting TuxGuitar with an old version config file on disk (i.e. without any value for this new parameter), I expected the new parameter to take its defined default value. But yet the new parameter is not set (remains `null`).

See [TGConfigPropertiesHandler.java](https://github.com/helge17/tuxguitar/blob/f5fafce1e8b591f898e3c73f1b983857d555e7c9/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigPropertiesHandler.java). There is an attempt to read first default values, then to override them with values read from stored config file:
```
public void readProperties(TGProperties properties, String module) throws TGPropertiesException {
	this.readDefaultProperties(properties, module);
	this.readStoredProperties(properties, module);
}
```
Unfortunately this does not work, the first call to `readDefaultProperties` is ineffective: when  `readStoredProperties` is called it ends up in [TGFilePropertiesReader.java](https://github.com/helge17/tuxguitar/blob/f5fafce1e8b591f898e3c73f1b983857d555e7c9/TuxGuitar/src/org/herac/tuxguitar/app/system/properties/TGFilePropertiesReader.java), where the previously loaded defaults are cleared!
```
if( file.exists() ){
	((TGPropertiesImpl)properties).clear();
	((TGPropertiesImpl)properties).load(new FileInputStream(file));
```

So, the stored properties do not *override* default values, but *overwrite* them with the content of old config file, leaving new parameter to `null`. At one point this will necessarily propagate to a null pointer exception...

Edit: a simple way to reproduce without instrumenting code
delete "color.play.note=255,0,0" line from tuxguitar.cfg (stored in ~/.config/tuxguitar/config on Linux), start TuxGuitar and open menu Tools/Settings. This raises an exception

**Comment by helge17** [comment]
The pull request #32 needs to be extended to the Android version. Currently the APK does not build.

**Comment by helge17** [comment]
Thank you!
