### ISSUE TITLE
Drum track causes Tuxguitar to stop responding

### ISSUE THREAD

**Issue by AndrehMars** [helge17/tuxguitar#320]
This only happens in SWT and stable versions. When trying to write to the drum staff, the program freezes and the only option is to forcefully close it.
Pre-release and Beta JFX versions work correctly

https://github.com/helge17/tuxguitar/assets/165952624/2982feaa-7f17-4a91-bc19-f0887be0f874

**Comment by guiv42** [comment]
reproduced on 1.6.2., only if fretboard is displayed, and if option "Display Note Text" is checked

**Comment by guiv42** [comment]
Should be fixed by #321 
to be tested on next pre-release (first one *following* 2024-04-03)

**Comment by AndrehMars** [comment]
Apologies for the delay
Bug fixed using tuxguitar-2024-04-16-master-windows-swt-x86_64
Thanks


https://github.com/helge17/tuxguitar/assets/165952624/aa8271a8-169d-4389-8147-ad89aca524b7
