### ISSUE TITLE
Tuxguitar/Linux not respecting `gtk-menu-images=0`

### ISSUE THREAD

**Issue by RJVB** [helge17/tuxguitar#326]
The title says it all: I have `gtk-menu-images=0` in my `~/.config/gtk-3.0/settings.ini` and tuxguitar 1.6.2 is not respecting that.

I can't remember if there used to be a choice between having a GTk and having a Qt5 GUI but if there was this may have been one of my reasons to go with the latter.

**Comment by guiv42** [comment]
Just for information: the Qt version has been deprecated, see #20 for more details.

**Comment by guiv42** [comment]
Extract from [gtk documentation](https://docs.gtk.org/gtk3/property.Settings.gtk-menu-images.html):
> Gtk Settings: gtk-menu-images
Deprecated since: 3.10
This setting is deprecated. Application developers control whether or not a GtkMenuItem should have an icon or not, on a per widget basis.

So I think we should not consider this setting.

**Comment by RJVB** [comment]
>Extract from [gtk documentation](https://docs.gtk.org/gtk3/property.Settings.gtk-menu-images.html):
>> Gtk Settings: gtk-menu-images
>Deprecated since: 3.10
>This setting is deprecated. Application developers control whether or not a GtkMenuItem should have an icon or not, on a per widget basis.

I'm always unpleasantly surprised when I reminded how respect for the user was lost/dropped by the Gtk devs.

BTW, I'd be happy too if you provide an option to disable icons in menus and/or widgets if that cannot already be done at the theme level. With their current huge size it just looks positively silly and unprofessional (or as if designed for young kids).

**Comment by guiv42** [comment]
Could you please create another feature request, to add an option to display/hide icons in menus?
