### ISSUE TITLE
Change the color of the font in the drum matrix

### ISSUE THREAD

**Issue by ycollet** [helge17/tuxguitar#327]
Today, the name of the drum elements in the matrix are in light grey. Not easy to read on a white background and when it's on a light blue, it's worst.
Can the font be turned into full black ?

**Comment by guiv42** [comment]
> Today, the name of the drum elements in the matrix are in light grey

What is your configuration?
Here: Linux openSuse tumbleweed (rolling release), KDE plasma 6. Name of drums elements appear in black font (with default settings)
![matrix](https://github.com/helge17/tuxguitar/assets/129443524/28ef3448-7219-42ff-8dc3-67e0c367c287)

**Comment by ycollet** [comment]
OK. I removed the .config/tuxguitar directory and it fixed the font problem. I close the ticket. Thanks !

**Comment by guiv42** [comment]
OK, thanks for your feedback.
Next time, I suggest to delete just the parameter causing your problem, so you don't loose your configuration. This single parameter will be reset to its default value.

**Comment by ycollet** [comment]
Yes :)
And from time to time a complete removal is a good idea too. The config was not too old, but I remember an old version of tuxguitar where a debug flag was still on a the config directory was absolutely huuuge ...
