### ISSUE TITLE
Linux: crash when printing to custom page size

### ISSUE THREAD

**Issue by RJVB** [helge17/tuxguitar#328]
I've been trying to print to a PDF file using the full page (0-size margins). The GTk print dialog doesn't seem to give control over the margins so I tried to create a custom entry for the A4 paper size with the margins all set to 0" ("A4full").

Selecting "A4full" as paper size and launching the print job crashes tuxguitar:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcc4b7a8f08, pid=21076, tid=21077
#
# JRE version: OpenJDK Runtime Environment SapMachine (17.0.2+8) (build 17.0.2+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM SapMachine (17.0.2+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4928r15.so+0x36f08]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P"
#
# An error report file with more information is saved as:
# hs_err_pid21076.log
Compiled method (n/a)   52403 2618     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fccb109d110,0x00007fccb109d498] = 904
 relocation     [0x00007fccb109d270,0x00007fccb109d2a8] = 56
 main code      [0x00007fccb109d2c0,0x00007fccb109d490] = 464
 oops           [0x00007fccb109d490,0x00007fccb109d498] = 8
Compiled method (n/a)   52403 2618     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fccb109d110,0x00007fccb109d498] = 904
 relocation     [0x00007fccb109d270,0x00007fccb109d2a8] = 56
 main code      [0x00007fccb109d2c0,0x00007fccb109d490] = 464
 oops           [0x00007fccb109d490,0x00007fccb109d498] = 8
Compiled method (n/a)   52424 2618     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fccb109d110,0x00007fccb109d498] = 904
 relocation     [0x00007fccb109d270,0x00007fccb109d2a8] = 56
 main code      [0x00007fccb109d2c0,0x00007fccb109d490] = 464
 oops           [0x00007fccb109d490,0x00007fccb109d498] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/SAP/SapMachine/issues/new
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```
[hs_err_pid21076.log](https://github.com/helge17/tuxguitar/files/14894100/hs_err_pid21076.log)

**Comment by guiv42** [comment]
My understanding: I really think it's **not** a TuxGuitar issue.
Refer to the log above: the error does not occur in TuxGuitar code (not even in the JVM). So there's nothing we can do here I think.

**Comment by RJVB** [comment]
>Refer to the log above: the error does not occur in TuxGuitar code (not even in the JVM). So there's nothing we can do here I think.

I notice that some function appears to be called with an invalid pointer, and that's something that *could* originate in TG code.

This crash isn't the only strange printing behaviour I observed. When I print to "A4+" (250x337mm; defined as 708x955 dots in the PPD) that size is shown correctly by the GTk print dialog (page setup panel) but the result is a PDF with 88x119mm page size.

**Comment by guiv42** [comment]
Coming back to the original problem described here (1st message in this issue): the main problem is I can find no way forward. Especially since I can reproduce exactly the same behavior without involving a single line of code from TuxGuitar. Issue seems located somewhere between SWT and Linux, and I cannot debug this.

About the other weird behavior you observed, I suggest creating another issue (which does not mean we will be able to solve it anyway!)
