### ISSUE TITLE
Keyboard shortcuts modifiers ignored in menu items (SWT)

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#33]
problem limited to SWT version (OK with JFX)
MenuItems display the associated keyboard shortcuts, BUT without modifiers. See Edit/Undo action, with default shortcut "Control+Z" : only "Z" is displayed
So, the same "Z" is displayed if shortcut is "Z" or "Control+Z"

probably introduced when upgrading SWT version in commit bbfd27fdabb46285954d0d3a49817b9bd9bf9f34 (1.5.6 correctly displays "Control+z") 

Unfortunately it seems the issue comes from SWT implementation, not from TuxGuitar's code.
TuxGuitar `SWTMenuItem.setText` correctly calls SWT `MenuItem.setText`, with "\t" separator between menu item description "Undo" and accelerator "Control+Z". This seems compliant with [SWT doc](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fwidgets%2FMenuItem.html&anchor=setText(java.lang.String)). Tried with many combinations, SWT only displays the last character after some separator:
- setText("Undo\tControl+z") displays "Z"
- setText("Undo\tControl z") displays "Z"
- setText("Undo\tControlz") displays nothing
- setText("Undo   Control+z") displays "Undo   Control+z", but all left-aligned (shortcut is supposed to be right-aligned, this is the purpose of "\t")

No idea how to fix this correctly :-(

Just an idea for a possible workaround: add a ToolTipText (ex "Undo\tControl+z", left-aligned) so that the complete shortcut appears when the mouse cursor goes over the menu item. Clearly not optimal... any other idea would be welcome!

Note: I have just tested the Linux configuration

**Comment by helge17** [comment]
I haven't tested very carefully, but it seems that the text after \t has to follow some conventions.

If you write "Ctrl" instead of "Control", e.g. setText("Undo\tCtrl+Z"), then "Ctrl+Z" is displayed in the menu, and in German it is even translated as "Strg+Z".

But simply replacing Control with Ctrl in TuxGuitar/dist/tuxguitar-shortcuts.xml doesn't help: Then the shortcuts for Control are displayed correctly, but they don't work anymore...

**Comment by helge17** [comment]
You need to change tuxguitar-shortcuts.xml AND the java code, then it should work.

I tried the following:

`$ sed -i s'/Control/Ctrl/g' TuxGuitar/dist/tuxguitar-shortcuts.xml ./TuxGuitar-viewer/src/org/herac/tuxguitar/app/system/keybindings/KeyBinding.java ./TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/resource/UIKey.java ./TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/resource/UIKeyLabel.java`

Now the key combinations work on Linux, Windows and FreeBSD, SWT and JFX, and are displayed correctly in the GUI. MacOS remains untouched.

**Comment by guiv42** [comment]
Don't know what to think about this. It would mean aligning TG's internal representation to SWT, so it looks more like a workaround to me: it will only work until SWT implementation changes once again.
I'm not telling I have a better solution to propose anyway.
What's the behavior when a user's config file from a previous version is already present? Does it correctly import shortcuts with Control modifier?

**Comment by helge17** [comment]
The internal representation of TG is somehow arbitrary, so "Ctrl" can be just as good or bad as "Control".
Aligning the internal representation of TG with SWT has the advantage that the key shortcuts displayed in the Key Binding Editor are the same as in the menu.

However, with this change, all keyboard shortcuts in the user preferences will no longer work after an update. The user must delete their ~/.config/tuxguitar/config/shortcuts.xml, but only when updating from a beta version to the new one.

Until 1.5.6, TG created a new settings directory after each update, probably to avoid such problems. When a user updates from 1.5.6 to our version here, the directory changes again, so all user settings are lost anyway (hopefully for the last time).

But I agree that this is more of a workaround than a solution. Probably the way shortcuts are handled needs to be reworked somehow, but maybe that should be done after we decide which toolkit to use in the long run (SWT, JavaFX, QT).

**Comment by guiv42** [comment]
OK, I'm aligned with your analysis. I just suggest to add a comment in the code where "Ctrl" string is defined, stating explicitly that this value is inherited from SWT v4.13.
If if changes again one day it should be possible to change xml file import to handle several formats.
And as said before, I have nothing better to propose. A new dependency to jface would only make sense if all the ui (accelerators included) is fully handled by SWT, which is not the case today

**Comment by helge17** [comment]
The fix is now committed with c414f89.

It seems that also the other strings have to be the same as in SWT to display the shortcuts (tested with "Shift" and "F12"). I have added a comment to UIKey.java.

I'm not sure if the file UIKeyLabel.java is still needed; you can delete it and TG builds for all platforms anyway.

**Comment by guiv42** [comment]
Great!
Eclipse cannot identify any use of UIKeyLabel class either, so I would vote for its deletion
