### ISSUE TITLE
Feature request: improvement of user interface for tuplets

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#333]
This is really a pain point for me when I edit a tab: user interface for tuplets could really be improved.
Two issues:

1. "Triplet" button appearance in edit toolbar does not show if it's active or not
Consequence: when typing a new note, it's impossible to know if the created note will be a triplet or not.
See video below.
At both instants 00:03 and 00:16, my intention is to create an eighth. In both cases, the appearance of the "Triplet" button in toolbar is exactly the same.
First case it creates an eighth, second case an unexpected triplet

2. Representation of time divisions is inconsistent
*Checkboxes* are displayed in drop-down list when triplet button is clicked.
But they behave like *radio buttons*: clicking an already checked item leaves it checked.

Combination of these 2 issues is problematic. Sometimes unexpected triplets appear, and the procedure to remove them is counter-intuitive:
- trying to uncheck option fails: see video, at time 00:20 my intention is clearly to remove the unexpected triplet -> it fails
- the required action is to deactivate a button whose representation does not show it is active, see 00:24

https://github.com/helge17/tuxguitar/assets/129443524/40ae7004-7811-42a9-abf5-c916b06ca7ac

note: video here corresponds to SWT version. With JFX version, the button's appearance issue is even worse, as all buttons are concerned, see #51. Furthermore, in JFX configuration only triplets are available, see #121

**Comment by guiv42** [comment]
The activation status of "Triplet" button is not shown, just because SWT does not enable this.
This button has a drop-down list associated, so it cannot be "checked". See [SWT doc](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/widgets/ToolItem.html):
`Only one of the styles CHECK, PUSH, RADIO, SEPARATOR and DROP_DOWN may be specified.`

The only alternative I can think of: change button icon depending from button activation status. Here is a preview of what it could look like:

https://github.com/helge17/tuxguitar/assets/129443524/248c705d-fd33-4c91-a25c-fb2f7c6b6b8c

Graphically it's sub-optimal, but I could not find any better. And as I tried to play a bit with it, I really see an added value.

@helge17 : what do you think of this solution?
This would require to create 2 new icons "division-time-checked" , for bright & dark skins.

**Comment by helge17** [comment]
> what do you think of this solution?

Would it be possible to select a separate icon for each available tuplet (none/3/5/6.../12/13)? I could then create the corresponding icons division-time-none.png, division-time-3.png, division-time-5.png and so on. This way, when you enter a new note, you would immediately see whether it will be a normal note or a tuplet and which tuplet it will become.
This would also avoid the problem of having to mark the button active or inactive: the button itself is always active and shows the current tuplet setting.

**Comment by guiv42** [comment]
> Would it be possible to select a separate icon for each available tuplet (none/3/5/6.../12/13)?

This is for sure an interesting option. Possibly we could also add a radiobutton "None" in the drop-down list?
I'll prototype this with dummy icons, so we can test the user interface

**Comment by helge17** [comment]
> Possibly we could also add a radiobutton "None" in the drop-down list?

Would make sense, yes.

**Comment by guiv42** [comment]
I would say the concept looks pretty good
You can have a try in my test branch: https://github.com/guiv42/tuxguitar/tree/testTupletsUI

This is just a prototype. I created dummy icons, only for Breeze skin.
I'm not quite sure what we should do for the label of the first item in drop-down list. Yet it's simply "1", but we could as well replace it by a new translatable string (e.g. "None", or "Normal" may be more clear?)

**Comment by helge17** [comment]
Your test branch looks good, thank you!

Commit 2d59d31 adds the division-type-*.png icons for all skins. I hope they are ok, just let me know if I should change something.

I will delete the old icon division-type.png as soon as your code changes are commited to master.

For division-type "none" I used a simple minus "-" sign in the icon. I think the "1" is a little misleading, a "-" would be clearer, but a translatable string "none" would be the best solution.

I would also suggest the following:
- Move the Tied Note between Double-Dotted and the Triplet drop-down in the left toolbar
- Place vertical separators before Tied Note and the Triplet drop-down list in the left toolbar
- Move the Tied Note in the Beat menu into the Duration sub-menu under Double-Dotted, with horizontal separators above and below
- Add the Triplet drop-down list to the Beat - Duration sub-menu

Should I try to implement this?

**Comment by guiv42** [comment]
thanks for the icons!

Dynamic selection of the tuplet-specific icon is now merged (#390). I also deleted the now unused "division-type.png" icons.

About your other suggestions, I would say it's up to you. From my perspective, the most annoying issue is now solved.
Just tell me if you think I can help

**Comment by helge17** [comment]
Inserting vertical separators changes the behaviour of the left toolbar and the Beat->Duration submenu would need more work as it doesn't show the selected parameters unlike the Dynamic and Effect submenus.

So I would leave it as it is for now and close this issue if that's ok with you.

**Comment by guiv42** [comment]
sure, no problem
