### ISSUE TITLE
Remove confirmation "Do you want to apply changes now?"

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#334]
When changing the settings (under Tools -> Settings), TuxGuitar always asks "Do you want to apply changes now?". Does this confirmation make sense, has anyone ever clicked No? I think this dialog can be removed.

**Comment by guiv42** [comment]
> has anyone ever clicked No?

Not me!
OK for the removal of this dialog, good idea.

**Comment by helge17** [comment]
Thanks for the feedback, I'll take care of it.
