### ISSUE TITLE
Export Audio File does not work for Percussion Channel

### ISSUE THREAD

**Issue by Makoha** [helge17/tuxguitar#350]
Steps to reproduce:
1. Open or create a tab that contains a Percussion Channel (DrumKit) beat.
2. `File` -> `Export` -> `Export Audio File`
3. The percussion track in the output audio file does not sound like a drum kit, but the sound will depend on the selected channel "Program"/"Bank". (Example: `Program #0` sounds like a piano)

Bug present in version 1.6.0, 1.6.2 and the latest beta release (tuxguitar-2024-04-13-master-windows-swt-x86_64)
Last seen working in version 1.5.6

**Comment by guiv42** [comment]
bisect leads to this commit: 4b40135096dec1bf56d36b27390e49c97e8eab02

@helge17 : I assume this was back-ported from 2.0beta fork?
Unfortunately I cannot test with 2.0beta: trying to export an audio file throws an exception

**Comment by Makoha** [comment]
Yes, bug is caused due to a small change in `MidiSequenceParser.java`

Original:
```java
	private void addChannel(MidiSequenceHelper sh, TGChannel channel, int track) {
		if((this.flags & ADD_MIXER_MESSAGES) != 0){
			int channelId = channel.getChannelId();
			long tick = getTick(TGDuration.QUARTER_TIME);
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.VOLUME, fix(channel.getVolume()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.BALANCE, fix(channel.getBalance()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.CHORUS, fix(channel.getChorus()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.REVERB, fix(channel.getReverb()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.PHASER, fix(channel.getPhaser()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.TREMOLO, fix(channel.getTremolo()));
			sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.EXPRESSION, 127);

			if((this.flags & ADD_BANK_SELECT) != 0) {
				sh.getSequence().addControlChange(tick, track, channelId, MidiControllers.BANK_SELECT, fix(channel.getBank(), 0, 128));
			}
			sh.getSequence().addProgramChange(tick, track, channelId, fix(channel.getProgram()));
		}
	}
```
Change:
```java

	private void makeTrackChannel(MidiSequenceHelper sh, TGChannel channel, TGTrack track) {
		if((this.flags & ADD_MIXER_MESSAGES) != 0){
			int channelId = channel.getChannelId();
			long tick = getTick(TGDuration.QUARTER_TIME);
			int trackNum = track.getNumber();
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.VOLUME,fix(channel.getVolume()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.BALANCE,fix(channel.getBalance()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.CHORUS,fix(channel.getChorus()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.REVERB,fix(channel.getReverb()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.PHASER,fix(channel.getPhaser()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.TREMOLO,fix(channel.getTremolo()));
			sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.EXPRESSION, 127);
			if(!channel.isPercussionChannel()){
				sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.BANK_SELECT, fix(channel.getBank()));
			}
			sh.getSequence().addProgramChange(tick,trackNum,channelId,fix(channel.getProgram()));
			sh.getSequence().addTrackName(tick,trackNum,track.getName());
		}
	}
```

To be exact, the lines:
```java
if(!channel.isPercussionChannel()){
	sh.getSequence().addControlChange(tick,trackNum,channelId,MidiControllers.BANK_SELECT, fix(channel.getBank()));
}
```

Should be changed to something closer to the original, like:
```java
if((this.flags & ADD_BANK_SELECT) != 0) {
	sh.getSequence().addControlChange(tick, trackNum, channelId, MidiControllers.BANK_SELECT, fix(channel.getBank(), 0, 128));
}
```

Do you see any problems with this change @helge17 ?

**Comment by Makoha** [comment]
To provide a bit more detail, the `TGSynthSongWriter.java` is where the `Export Audio File` process starts.
The process is expecting a `MidiControllers.BANK_SELECT` ControlChange MIDI event to be triggered in order switch between instruments. This was previously accomplished by constructing the `MidiSequenceParser` with the `MidiSequenceParser.ADD_BANK_SELECT` flag. But due to the changes in commit: 4b40135, that flag was no longer checked in the `MidiSequenceParser`. Instead, every instrument send the `MidiControllers.BANK_SELECT` ControlChange MIDI event, except for percussion channels.

**Comment by guiv42** [comment]
@Makoha : it's a part of code I've never looked at. So, if you feel confident about a fix don't hesitate to send a pull request.

**Comment by Makoha** [comment]
The origin for this bug seems to have been introduced in `tuxguitar-2.0beta`, which I assume was then ported into this repository.
Prior to commit 41c0533, this `isPercussionChannel()` check was present.
It was then change to an `ADD_BANK_SELECT` flag check in commit 41c0533, probably due to the `TuxGuitar-synth-export` plugin (aka. `Export Audio File`) being added on that same day. (commit 24e2406)
For some reason this `ADD_BANK_SELECT` flag check was reverted/overwritten in the `tuxguitar-2.0beta` fork.

**Comment by guiv42** [comment]
> The origin for this bug seems to have been introduced in tuxguitar-2.0beta, which I assume was then ported into this repository.

Yes, I confirm issue was back-ported from (now abandoned) 2.0beta fork into this repo.
It's clearly not the first time we back-port an issue from 2.0beta. There are a lot of great ideas in this fork, some of them still deserve to be considered for merging here. But unfortunately there are many issues also. Since I could not find any binary release of 2.0beta, my interpretation is that this fork has missed a wide enough user base for testing. Possibly it's only been used by people able to build it (?)

@Makoha Thank you very much for the fix. Can we close this issue now?

**Comment by helge17** [comment]
> Since I could not find any binary release of 2.0beta, my interpretation is that this fork has missed a wide enough user base for testing. Possibly it's only been used by people able to build it (?)

You can try out my builds on https://github.com/helge17/tuxguitar-2.0beta/releases/ . I don't know of any other binary packages.

**Comment by helge17** [comment]
> bisect leads to this commit: [4b40135](https://github.com/helge17/tuxguitar/commit/4b40135096dec1bf56d36b27390e49c97e8eab02)
> 
> I see this was back-ported from 2.0beta fork. Unfortunately I cannot test with 2.0beta: trying to export an audio file throws an exception. @helge17 : what was exactly the purpose of this commit? We probably need to revert some modifications, but the difficult part is to keep the added value

This commit has been discussed and tested in #85 . Sorry for having introduced a bug!

**Comment by guiv42** [comment]
> You can try out my builds on https://github.com/helge17/tuxguitar-2.0beta/releases/ . I don't know of any other binary packages.

I could build 2.0beta, thanks.
I was just mentioning the absence of installable binaries as a possible explanation for the quality issues of this fork. Without any direspect: great job done, by developers surely more skilled than I am. But without enough contributors for testing it's difficult to reach a correct quality level.

> Sorry for having introduced a bug!

I've also ported a few issues from 2.0beta here in this fork ;)
Definitely we shall be *very* cautious when re-using code from 2.0beta.

**Comment by Makoha** [comment]
@guiv42 Yes, I think this issue can be closed now.
I have just compared the hash of an audio file produced by the latest pre-release against the hash of an audio file produced by version 1.5.6, and they are completely identical.

**Comment by guiv42** [comment]
thanks!
