### ISSUE TITLE
Export Gervill Audio File plugin fails

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#367]
see discussions #185 and #366

TuxGuitar 1.6.2, Linux openSuse tumbleweed.
Steps to reproduce:
- open TuxGuitar
- in menu "Tools/Plugin", activate "Gervill Plugin"
- click menu "File / Export / Export Gervill audio file"
- leave all options to their default values, click OK and select a target file

expected result: an audio file is created
observed result: Error
![20240427_195710](https://github.com/helge17/tuxguitar/assets/129443524/5487d89e-33ff-4777-8494-fedaac1853ff)

```
org.herac.tuxguitar.action.TGActionException: class org.herac.tuxguitar.io.gervill.MidiToAudioSynth cannot access class com.sun.media.sound.SoftSynthesizer (in module java.desktop) because module java.desktop does not export com.sun.media.sound to unnamed module @10e6c76d
```

**Comment by guiv42** [comment]
Unless anyone has a better idea, I suggest depreciating TuxGuitar-gervill module

**Comment by helge17** [comment]
At least for Android we need a replacement for Gervill, as it is the only output method.

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/ca53227e-1fc1-46ed-94b2-54e9a9745710)

**Comment by guiv42** [comment]
1. About the **gervill plugin for desktop app**
This is what is displayed when clicking on plugin info button:
![20240428_111612](https://github.com/helge17/tuxguitar/assets/129443524/83e35d67-5d31-4e3d-bd50-a9600d629a2b)

The referenced website:
- has an invalid certificate
- if its certificate is accepted, webpage displays "We're sorry the java.net site has closed."

Note: we have the same issue in our [README](https://github.com/helge17/tuxguitar/blob/6e900a472b9617e77c9c083b476bdd27029b0b86/README.md?plain=1#L19), it may be worth deleting this link.

So, somehow user is informed that this plugin cannot work. Considering that:
- issue is present since quite a long time
- as far as I know, nobody complained (neither here in github nor on historic sourceforge repo)
- feature is not documented in user help

I think we should depreciate `TuxGuitar-gervill` module. Note that I don't know exactly all the features provided by this module...
Note: at least in a short term perspective `gervill` module can remain present, as gervill code has been [copied in TuxGuitar code base](https://github.com/helge17/tuxguitar/tree/master/desktop/gervill) at some point. So, removing `TuxGuitar-gervill` module does not disable "Gervill" output in "Settings/Sound/MIDI port" option.

2. In **Android app**

@helge17 you're right, usage of **Gervill in Android app** is clearly an issue. I suggest to de-correlate the 2 problems:
- depreciate TuxGuitar-gervill for desktop app, then close this issue
- open a dedicated issue for Android, maybe with a tag "Android-specific issue"

There's really so much to do in the Android app...

**Comment by helge17** [comment]
That's fine with me. But maybe we should release 1.6.3 first and then deprecate TuxGuitar-gervill for desktop?

**Comment by guiv42** [comment]
Maybe we should check which features this plugin exactly provides?
If it's just the Gervill audio export, I don't see any added value in keeping a plugin that doesn't work.

**Comment by helge17** [comment]
Gervill appears in various places in TuxGuitar, it’s quite confusing.

1. File → Export → Export to Gervill Audio File: This function indeed seems to be provided by the Plugin named "Gervill Plugin". This is broken, as described in this bug report, so indeed it can be removed.
2. Tools → Settings → Sound: MIDI Sequenzer: TuxGuitar Sequenzer, MIDI Port: Gervill
3. Tools → Settings → Sound: MIDI Sequenzer: TuxGuitar Sequenzer, MIDI Port: TuxGuitar Synthesizer and Plugin "TuxGuitar Synth - Gervill Extension" enabled. Now you can access View → Show Instruments → Channel Settings of one Instrument → + (Set MIDI receiver) → MIDI Processor Type: gervill.

I tested this on Linux only. Also all other OS make use of Gervill.

I think the code in desktop/TuxGuitar-gervill/ only provides the Gervill Export function (1.).
2. & 3. are provided by the code in desktop/TuxGuitar-synth-gervill/.

So I would propose the following:

- I deprecate the "Gervill Plugin" (desktop/TuxGuitar-gervill/) and I test the result on all OS before committing the change to master.
- Then we close this issue, as @guiv42 suggested.
- The rest of the „Gervill story“ will be discussed in #185, #366 and subsequent issues.

**Comment by helge17** [comment]
Commit fa20fb1 deprecates the "Export to Gervill Audio File" Plugin. I did not notice any side effects on the other Gervill features.

**Comment by guiv42** [comment]
Thanks!
