### ISSUE TITLE
Ignoring selected `Save as type`

### ISSUE THREAD

**Issue by Makoha** [helge17/tuxguitar#369]
Steps to reproduce (on windows):

1. Create a new tab
2. `File` -> `Save As`
3. In the `Select type as:` drop-down select `Guitar Pro 5`
4. Click `Save`

The saved file will have the `.tg` extension, but the expected extension would be `.gp5`

**Note:** This only seems to happen in the pre-releases. (Not in version 1.6.0 or 1.6.2)
I initially encountered this in pre-release `tuxguitar-2024-04-13-master-windows-swt-x86_64`.

When trying it out on Linux the `.tg` extension is visibly pre-filled in the save dialog (I don't know if this is expected, since other programs like `LibreOffice` does not seem to do this.)

**Comment by guiv42** [comment]
Tested and reproduced on Windows 10:
- OK with 1.6.2
- KO with c0dff05cc8d1bf93c49c8cc0389c02ec9e2972a7 (latest commit when writing this)

In both cases, when "Save As" windows opens, file name field is set to "untitled.tg". When selecting ".gp5" format in drop-down list:
- with 1.6.2 file name field is replaced by "untitled.gp5"
- with c0dff05cc8d1bf93c49c8cc0389c02ec9e2972a7 it remains "untitled.tg"

No idea of any possible cause for that, I'll try intermediate versions (bisect)

**Comment by buryoutougen** [comment]
As a workaround, it's still possible to save in .gp5 format if you write the .gp5 extension explicitlty in the filename.

**Comment by guiv42** [comment]
tuxguitar-2024-05-06-master-windows-swt-x86_64.zip tested on Win10: issue is fixed
