### ISSUE TITLE
Doesn't start properly

### ISSUE THREAD

**Issue by aironsouza** [helge17/tuxguitar#377]
Hello, just installed the flatpak version (also tried the .rpm stable) on Fedora KDE, latest version, and the app doesn't start. I get this screen and nothing more.

![image](https://github.com/helge17/tuxguitar/assets/7475132/69b4d309-1554-4f4a-b735-0eaad7aa76a4)

When I run it via terminal I get the following:

![image](https://github.com/helge17/tuxguitar/assets/7475132/adb72c2b-a2ab-4fe6-8e9c-d308769d4454)

**Comment by guiv42** [comment]
Hi, it seems this issue is a duplicate of #323, also mentioned here: https://github.com/flathub/ar.com.tuxguitar.TuxGuitar/issues/35

Until we publish a new version you can use .rpm of latest [pre-release](https://github.com/helge17/tuxguitar/releases)

**Comment by aironsouza** [comment]
Oh, I see. Thank you.
