### ISSUE TITLE
Rationalize player icons

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#379]
Player icons are defined by pairs, with suffixes `_1` and `_2` :

Example: for Oxygen skin, [transport_first_1](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar/share/skins/Oxygen/transport_first_1.png) and [transport_first_2](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar/share/skins/Oxygen/transport_first_2.png)

However, for most skins the 2 icons of a pair are exactly identical. Exceptions:
- blue_serious skin: all icons with suffixes _1 and _2 differ
- ersplus skin : all icons with suffixes _1 and _2 differ
- Lavender skin: transport_icon_last_1 and _2 files are different, even if visually I don't see the difference, all other icons _1 and _2 are identical

Looking in the code (at several places), icon `_1` or `_2` is selected considering condition `MidiPlayer.isPaused()`.
However this does not correspond to any logical state of the midi player. Whenever user clicks *pause* or *stop*, the player *stops*.
See [this discussion](https://github.com/helge17/tuxguitar/issues/365#issuecomment-2108482591)

Some cleanup seems needed here.

**Comment by helge17** [comment]
I would say that the dark controls should mean „Player is turned off“ (replay stopped) and the bright controls mean „Player is turned on“ (playing or paused).

The player in 1.5.6 and in the new version behaves slightly differently, see green/red markings.

![image](https://github.com/helge17/tuxguitar/assets/5897631/b015d9ae-a3f5-42a7-a512-85f42bb49e7d)

So 1.5.6 distinguishes between the "Pause" status and the "Stop" status, but makes quite unexpected cursor movements.

The new version places the cursor more logically, but does not handle the "Pause" status correctly.

**Comment by guiv42** [comment]
Thanks for this analysis, this is more clear.

> So 1.5.6 distinguishes between the "Pause" status and the "Stop" status, but makes quite unexpected cursor movements.

I'd say this is questionable. Start playing, then pause somewhere. Player is considered "paused". But is it really? Start editing the song, adding or removing measures. Can we still considered the player is "paused"? Since, when hitting "play" the starting point of the player cannot even be compared with the place where "pause" was hit?

> The new version places the cursor more logically, but does not handle the "Pause" status correctly.

That's right. In fact it just means the concept of "paused" status is not well defined.

So, how can we move forward?
My proposal: just keep one single version for each icon

**Comment by helge17** [comment]
> My proposal: just keep one single version for each icon

You're right. So I will rename all transport*_1.png icons to transport*.png and remove the transport*_2.png icons, ok?

**Comment by guiv42** [comment]
> So I will rename all transport*_1.png icons to transport*.png and remove the transport*_2.png icons, ok?

OK, thanks!
I have updated the code (#385): `transport*_2.png` icons are no more used and can be safely deleted.
Last thing to do in the code after renaming `transport*_1.png` to `transport*.png` is to update file names in [TGIconManager](https://github.com/helge17/tuxguitar/blob/0c6602e1edf2e03912bce88b10560339a99e085b/desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/icons/TGIconManager.java#L302)

Notes:
- minor bug fixed: label of 1st menu item of "Player" menu was always "Start", regardless of player status. Icon was correctly updated (Play/Pause)
- minor bug still present in TuxGuitar tray: 1st item is always "Play" (text + icon), regardless of player status. New issue to be created
