### ISSUE TITLE
Can't install tuxguitar-1.6.2-linux-swt-x86_64.deb on Ubuntu 24.04 Noble

### ISSUE THREAD

**Issue by eris23** [helge17/tuxguitar#387]
tuxguitar-1.6.2-linux-swt-x86_64.deb depends on libwebkit2gtk-4.0-37

Ubuntu 24.04 Noble has libwebkit2gtk-4.1-0

**Comment by guiv42** [comment]
duplicate of #347 
Please use a more recent [pre-release](https://github.com/helge17/tuxguitar/releases) until a new release is published
