### ISSUE TITLE
A question about Files conversion

### ISSUE THREAD

**Issue by thedoggaming16** [helge17/tuxguitar#391]
Hello, I'm asking if it's possible to convert only one file and not a whole folder with files. 

I know it's possible to convert all files in one folder with this option but if I want to convert only one files (Example GP5 to Midi), I'm wondering if it's possible to do this. Thanks !
![image](https://github.com/helge17/tuxguitar/assets/74026429/47b9017b-4846-483d-93f7-290ba7ae4ddb)

**Comment by guiv42** [comment]
I'm not sure I understand your question.
Just open the gp5 file, then use menu "Export/Export to Midi"

**Comment by thedoggaming16** [comment]
Ah ok thanks ! (It was about converting just one file,)
