### ISSUE TITLE
TEF file isn't imported with all bars

### ISSUE THREAD

**Issue by adrian-vogler** [helge17/tuxguitar#400]
Which version of TuxGuitar you are using: TuxGuitar 1.5.6
On which platform and which version: Windows 10
[Stan Ridgway - Camouflage - StreicherG.zip](https://github.com/helge17/tuxguitar/files/15473955/Stan.Ridgway.-.Camouflage.-.StreicherG.zip)
there are 2 different .tef files in your archive, BOTH are causing the issue.

Screenshot of TablEdit showing measure 107 and the following ones is attached.
![image](https://github.com/helge17/tuxguitar/assets/95128254/99543a5e-e18f-46f8-9422-cc7ea19bb268)

**Comment by guiv42** [comment]
precision: 362 bars in original song, see #399

**Comment by guiv42** [comment]
@adrian-vogler : fix is now available since pre-release 1.6.3beta2

**Comment by adrian-vogler** [comment]
Great! Thank You!!
