### ISSUE TITLE
String skipping in chords when importing MIDI files.

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#409]
when a MIDI file is imported, notes are assigned strings according to guitar tuning and pitch. this produces string skips in some chords that would typically be played at a higher position on the fretboard.

in general, chords would be played on sequential strings so this should be the desired output where possible. for chords, the import should **start** from the **lowest note** and process notes sequentially ascending in pitch. this way **each** note would be **placed on the next available string** above the last note, instead of the string it would be played on if it were not in a chord.

Importing MIDI files currently produces the result shown in the first bar but should look like the second bar?
```
(1)         (2)
|-----------|-----------|
|-----2--1--|-----------|
|--3--1--0--|--3--6--5--|
|--3--------|--3--6--5--|
|--1--4--3--|--1--4--3--|
|-----------|-----------|
```

**Comment by guiv42** [comment]
Hi @belfie13 
*midi* files are made to be played by a *machine* (sequencer/synthesizer)
*tablature* files are made to be played by a *human* musician

So, translation is definitely tricky. The level of information contained in each document format is designed for different purposes. Just refer to [user documentation](https://www.tuxguitar.app/files/1.6.3/desktop/help/file_formats.html), see "midi file import" section: `please bear in mind that TuxGuitar is basically a tablature editor and not a MIDI editor, so don't expect magical results`

Trying to optimize allocation of notes to string could consider many (conflicting) criteria:
- try not to loose notes
- horizontal distances (max/min fret) between notes of a chord
- vertical distances (max/min string) between notes of a chord: the problem you mention here
- horizontal and vertical distances with preceding and following chords
- right hand technique: fingers? pick? tapping?
- effects, e.g. strong bends are more comfortable near the middle of fretboard
- transitions: slide, hammer-on/pull-off, trills, let ring, give very strong constraints on successive notes allocation
- sound: the same note on different strings does not sound exactly the same
- sound: in your example, adding dead notes (left-hand muted) on the G string in the first bar could produce percussive sound, that could be an explicit intention of the guitarist
- personal taste of the guitarist
- ...

These are just example, the list is for sure not exhaustive. A midi file does not provide any data that could significantly help in this task.
Personally, I've been working for many years with *tablature files* under guitar pro format found on the Internet. Even starting from very rich files, I don't think I played any song seriously without a manual rework of this allocation.

So, I don't plan to go any further on this topic. Another extract from user doc: `manual adjustment is generally required to fine-tune the result`

**Comment by belfie13** [comment]
yeah there's alot to go on, I typically have to spend a long time adjusting so i'll look into it as best as I can. even though it's probably a dead end 🦸‍♂️

**Comment by guiv42** [comment]
I'm trying to clean up a bit the list of open issues. No intention to implement anything about this issue on my side.
@belfie13 : can this issue be closed?

**Comment by belfie13** [comment]
Just want to add that MIDI is probably the only way to transfer songs to and from alot of apps (Logic Pro for example). the one thing that keeps happening (if you don't think this is enough then i'd say you can close it) is for example a power chord on the third fret (A) will import as (B) which is obvious and takes a long time to edit every time, this is basically my main workflow because i transfer to and from tux with midi for a few reasons.

could we just put a little check to avoid string skips?

i don't know, it's too much for me to understand what issues that brings because my playing style is mostly picked so i don't string skip alot. i would never play a power chord like that but that's just my style

```
------
------
----0-
-5--0-
-5----
-3--3-
(A)(B)
```

**Comment by guiv42** [comment]
> MIDI is probably the only way to transfer songs to and from alot of apps

To be honest I disagree on this point. MIDI is for sure a widely used data format for *sound*, or *music for synthesizers*. But considering scores/tablatures, this is a very poor data format. The de-facto standard for guitar tablature is guitar pro. It was one goal of musicXML to be one suitable data exchange format, TuxGuitar can for sure progress in this field.

> could we just put a little check to avoid string skips?

I personally don't plan to spend time on this subject. Feel free to have a look if you want! Currently the code which allocates notes to strings when importing MIDI is [there](https://github.com/helge17/tuxguitar/blob/8d371543a4ba3da367edb4b3b7db61853b3157f5/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java#L447)
