### ISSUE TITLE
Mac OS 12.7.1 will not allow installation

### ISSUE THREAD

**Issue by PLawrence03** [helge17/tuxguitar#411]
OS returns an error message "“tuxguitar-1.6.3-macosx-swt-cocoa-x86_64” cannot be opened because the developer cannot be verified." I have been trying to download:
 [tuxguitar-1.6.3-macosx-swt-cocoa-x86_64.app.tar.gz](https://github.com/helge17/tuxguitar/releases/download/1.6.3/tuxguitar-1.6.3-macosx-swt-cocoa-x86_64.app.tar.gz)

How can I get around this?

**Comment by guiv42** [comment]
Hi
I have no macOs machine available so I cannot analyze in details. However this looks like a very classical issue in Apple environment: we haven't payed for the Apple developer license, and Apple is globally a closed eco-system.
A quick search on the Internet should help you bypass this issue (e.g. I found these articles: [1](https://www.cnet.com/tech/computing/how-to-install-unidentified-app-on-a-macbook/), [2](https://www.lifewire.com/fix-developer-cannot-be-verified-error-5183898)), detailed solution might depend from macOS version

**Comment by PLawrence03** [comment]
Thank you. Sent from my iPhoneOn Jun 9, 2024, at 6:11 AM, guiv42 ***@***.***> wrote:﻿
Hi
I have no macOs machine available so I cannot analyze in details. However this looks like a very classical issue in Apple environment: we haven't payed for the Apple developer license, and Apple is globally a closed eco-system.
A quick search on the Internet should help you bypass this issue (e.g. I found these articles: 1, 2), detailed solution might depend from macOS version

**Comment by guiv42** [comment]
@PLawrence03: I'm closing issue, since it seems external to TuxGuitar
You can re-open it if needed.

**Comment by belfie13** [comment]
you have to option click the file and select open from the menu @PLawrence03

**Comment by PLawrence03** [comment]
If you mean option click the file from the Finder window, all that does is display the Tux icon in the column to the right. Any other suggestions?

Peter L. Lawrence
85 Knollwood Lane
Avon, CT 06001
