### ISSUE TITLE
Deadnotes (x) not displayed in score staff

### ISSUE THREAD

**Issue by Tungurahua** [helge17/tuxguitar#414]
Thanks for maintaining this great piece of software!

If a deadnote is entered the respective notehead (x) shows up in tabulature but not in the score staff.  

![image](https://github.com/helge17/tuxguitar/assets/2544688/23f413c9-91c7-4b1d-945b-a3593e011c7b)

**Comment by guiv42** [comment]
Warning, several graphical representations should be needed, especially to show the difference between a half and a quarter. Differences between other notes duration should be visible thanks to note's stem

**Comment by guiv42** [comment]
Forget my preceding comment and let's keep it simple. Yet in percussion tracks, there is no difference between representations of a (x) note if it's a quarter or a half.

Feature implemented by #445
