### ISSUE TITLE
Midi of several tracks is imported to a single track

### ISSUE THREAD

**Issue by alexisguerreroabg** [helge17/tuxguitar#418]
When importing a midi file containing several tracks, a unique track is created that merges them. When importing from Ardour the same MIDI file, this problem does not happen.
[MidiFile.tar.gz](https://github.com/user-attachments/files/15813063/MidiFile.tar.gz)

**Comment by guiv42** [comment]
Refer to [user help](https://www.tuxguitar.app/files/1.6.3/desktop/help/file_formats.html): menu Help/Documentation, then go to section "supported file formats/midi import/ midi file types"

> There are two different MIDI file types:
> - A type 0 file contains a single MIDI track, possibly with sounds played by different instruments.
> - A type 1 file can contain one or more MIDI track(s), with one instrument per track.
> 
> Currently, TuxGuitar can import type 1 files quite correctly. Type 0 files are also correctly imported if they contain a single instrument. When importing a type 0 file with multiple instruments, TuxGuitar merges everything into a single track. This can of course lead to unwanted side effects, such as the loss of notes and/or incorrect tuning selection. In this case, you should consider converting the file to type 1 with an external MIDI application before importing it.

A feature request already exists for this (#205), so I close this issue (duplicate)
