### ISSUE TITLE
"tied note" icon is confusing

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#42]
"Tied note" icon (in all themes) represents a note tied to *the following note*, the "tied" symbol is oriented to the right.
However, it ties current note to *the preceding one*, oriented to the left. So it's a bit confusing.
See screenshot:
![Screenshot_20230521_113256](https://github.com/helge17/tuxguitar/assets/129443524/0806ed5f-c6ac-4bb8-aae2-5af5e8421bec)

It would be very easy to edit the existing png icons for the different themes and change orientation of the "tied" symbol. However I don't think it's the right method.
I assume all icons are inherited from some vector graphics defined somewhere else?

**Comment by helge17** [comment]
There are SVG graphics for the older blue_serious and ersplus skins (skin.svg), but I can't find vector graphics for Breeze/Lavender/Oxygen. You can probably find SVG graphics for the default icons, since the skins are derived from KDE themes, but I don't know where to find music-related icons.

It seems that in the long run a new skin will be needed. The Symbolic skin from 2.0beta may be a good alternative; it has SVG files in TuxGuitar/icon-src/.

**Comment by guiv42** [comment]
Thanks for your answer
So, until we introduce (or switch to) a new theme, do you think it makes sense if I just "patch" the existing png icons?

**Comment by helge17** [comment]
Commit 191ed9e aligns the "tied note" icon with the TG score display. But to be precise, the tie symbol should go down in the score when the symbol is at the bottom of the notes:
![TG_tied_note](https://github.com/helge17/tuxguitar/assets/5897631/599c74df-b622-4af2-87f3-78f894efe08c)

**Comment by guiv42** [comment]
Yes !
I will try to invert the symbol direction in this case.
Then it would be logical to make the icon consistent. Example:
![tiednote](https://github.com/helge17/tuxguitar/assets/129443524/edf5e901-94da-4e51-a899-a9f6b36cf41d)

**Comment by guiv42** [comment]
Hi, I have submitted a pull request according to your proposal
I can easily push new png icons consistent with this new orientation, but only for Breeze, Lavender, and Oxygen: yet I don't know how to edit the svg
Or do you want to do it?

**Comment by helge17** [comment]
Icons are aligned now.

You can edit SVG files with Inkscape.
