### ISSUE TITLE
Exported audio is not complete in a SPECIFIC case mentioned 

### ISSUE THREAD

**Issue by SerjSX** [helge17/tuxguitar#431]
Today I wrote a sheet, and it basically starts with a slow tempo (like 40) and then there is repetition, then at some point I changed the tempo to 100. The problem showed up when I exported the audio file, and part of the sheet from the end was not included in the export! I went on to create another sheet, but with random notes though a similar structure with the repetitions and tempo changes, and it did the same. 

I attached the file here below, also the audio file. As you can see, it cuts in the end rather than including the entire sheet. This happens more with long sheets that have such structure, because when I tried to do something similar with a couple of measures and no repeitions : it wasn't being cut.

Here is the TuxGuitar file of the test sheet I used to test with similar tempos and repetitions with the exported audio file:
[test.zip](https://github.com/user-attachments/files/15928161/test.zip)
The issue is spotted in the end. I'm using MID export until this issue has been fixed, because MID does not have this issue.

Thanks in advance!

**Comment by guiv42** [comment]
reproduced on TuxGuitar v1.6.3 / Linux (openSuse tumbleweed) with provided test file

**Comment by guiv42** [comment]
Root cause: erroneous computation of song duration.
A simpler method to reproduce: just create a song with 1 bar at tempo 40bpm. Fill the bar with 16ths, and export to wav -> output was truncated.

That should be OK now

**Comment by guiv42** [comment]
@SerjSX could you please have a try with latest pre-release (>= 2024-06-23) and close issue if it's OK?

**Comment by SerjSX** [comment]
Fixed, thank you!
