### ISSUE TITLE
Symbols for upstroke and downstroke

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#442]
Up/downstroke are currently represented by down/up arrows (note the reverse order). TuxGuitar should use the usual symbols for upstroke and downstroke.

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/e164a796-bbe0-4c1a-9bf3-46c89e7fded5)

**Comment by helge17** [comment]
I realized that the up/down arrows are used for *brush* Up/Downstroke played with the fingers, the icons above are used for pick Up/Downstroke. TuxGuitar supports brush strokes, but not pick strokes. To clarify this, I have added the note "brush" to the menu items in Commit 945bee06abf94ec0d1e3245354c17e520300a307.

**Comment by nbkhope** [comment]
Why doesn't TuxGuitar support adding notation for downward and upward picking?

**Comment by guiv42** [comment]
TuxGuitar supports this since 2.0.0
