### ISSUE TITLE
(bug) Reverb Setting dosen't save 

### ISSUE THREAD

**Issue by thedoggaming16** [helge17/tuxguitar#447]
When I tried to put the reverb on my guitar, it dosen't save after quitting and reopening the tab

https://github.com/helge17/tuxguitar/assets/74026429/e900363c-4d76-484f-8433-e83759ee775f

**Comment by guiv42** [comment]
Please use TuxGuitar's native file format (.tg) when editing a song. That's the only way to make sure no data is lost. 
gp5 format is proprietary, and it's very difficult to guarantee full compatibility (I don'teven know if gp5 manages reverb).
Refer to [user help](https://www.tuxguitar.app/files/1.6.3/desktop/help/file_formats.html):
> We strongly recommend that you use TuxGuitar's own file format for your songs. The other formats may not support all features of TuxGuitar. These formats are mainly intended for exchanging files with other programs.
