### ISSUE TITLE
Feature Request: Key commands / keyboard short cuts for zoom in / out

### ISSUE THREAD

**Issue by rngdmstr** [helge17/tuxguitar#460]
Hey, small request, so I hope it wouldn't be too much trouble.

Could we get some key commands / keyboard shortcuts for zoom in and zoom out? + and - would be good choices.

I use Tuxguitar primarily for guitar chord charts and they are only useful if you're zoomed in fully. So, every time I open a project, I have to click View + Zoom In like 11 times before I can start working on it. 

Would make my life a lot easier :) Thanks!!!

**Comment by guiv42** [comment]
Hi

feature is already present. See menu Tools/Shortcuts, type "zoom" in first line of dialog (filter), and customize your own keyboard shortcuts for zoom in/out actions: double-click on action and type your shortcut
![20240711_083126](https://github.com/helge17/tuxguitar/assets/129443524/de4b54c5-a5ea-47d3-b3b2-d399a5ac9afd)

By the way, the easiest manner to zoom in/out is probably [Ctrl + mouse wheel], or [Ctrl + 2-fingers vertical swipe on touchpad] if you have no mouse.

**Comment by guiv42** [comment]
Closing issue, as already solved.
@rngdmstr just make sure you use latest release, that should be ok

**Comment by rngdmstr** [comment]
oh, splendid! thanks!
