### ISSUE TITLE
Dark Themes not working on Windows 11

### ISSUE THREAD

**Issue by HaegarTheHorrible** [helge17/tuxguitar#473]
When I select one of the dark skins, the icons turn bright, but the background color and menu skin remain light colored too.
This appearance persists upon restarting the app.
I had to revert to a bright skin, to have the app usable.

![tuxguitar-dark-skin](https://github.com/user-attachments/assets/3acb816f-8289-4a1b-adee-cf67532b1a73)

I tried uninstall and reinstallation.
Tried clicking "Defaults".
Tried to change colors in the tuxguitar.cfg file in my userprofile, but the app seems to overwrite that on start.
Tried to manually adjust colors in the "Styles" settings, but there is no "Background" or "Skin" color setting.

**Comment by guiv42** [comment]
closing issue: already known
duplicate (#465, #27)
