### ISSUE TITLE
Windows and Eclipse build

### ISSUE THREAD

**Issue by JLouhela** [helge17/tuxguitar#488]
Hi!

As a developer with Windows workstation and no proper Java background, I would like to be able to run the code in IDE and debug certain use cases. Is it possible to do it easily? Simply opening the project gives errors about missing SWT and I'm not sure how to address the SWT dependency through Eclipse.

As an occasional user of TuxGuitar I am looking to get into contribution. I have a background in software development but I don't have the expertise on Java projects and maven world.

Any tips appreciated!

With best regards,
Joni Louhela

**Comment by guiv42** [comment]
Hi,
I never tried on Windows, but there is a detailed documentation for Linux environment, see [contribute.md](https://github.com/helge17/tuxguitar/blob/master/doc/contribute.md).
It probably requires to be adapted for Windows. Typically, to install SWT you can refer to [install.md](https://github.com/helge17/tuxguitar/blob/master/INSTALL.md)

**Comment by JLouhela** [comment]
Somehow I missed the environment setup in the contribute.md, thanks!

It has more information than I expected, so I'll close this issue and work it from there.

**Comment by guiv42** [comment]
OK, and don't hesitate to ask for help if needed.
If you succeed to set up a correct environment in Windows to build/debug with Eclipse, don't hesitate to update contribute.md, other users might be interested.
