### ISSUE TITLE
installation on Mint 20 Ulyana

### ISSUE THREAD

**Issue by oxidian24** [helge17/tuxguitar#495]
Hello, I'm having trouble to install your package. It seems like some dependency. 
# sudo gdebi tuxguitar-1.6.3-linux-swt-amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Tento balík nelze nainstalovat
Dependency is not satisfiable: libfluidsynth3

# apt search libfluidsynth*
p   libfluidsynth-dev                          - Real-time MIDI software synthesizer (development fil
p   libfluidsynth-dev:i386                     - Real-time MIDI software synthesizer (development fil
i A libfluidsynth2                             - Real-time MIDI software synthesizer (runtime library
p   libfluidsynth2:i386                        - Real-time MIDI software synthesizer (runtime library

So is this for the latest Mint only like 21.3?

**Comment by guiv42** [comment]
> So is this for the latest Mint only like 21.3?

I don't know, I never tested on Mint. For sure we cannot test all distros and their various releases. deb package provided here has been packaged in debian environment.
@oxidian24: can you try with .tar.gz release? Just extract it somewhere and call `tuxguitar.sh`

**Comment by oxidian24** [comment]
I have tried the tar gz and I can run it. thanks

**Comment by guiv42** [comment]
good
So, can this issue be closed?

**Comment by oxidian24** [comment]
yes
