### ISSUE TITLE
The right scroll bar is not available during play

### ISSUE THREAD

**Issue by ycollet** [helge17/tuxguitar#503]
With the last version of tuxguitar (1.6.4), the right scroll bar is not available when the score is in play mode.
Once the score is stopped, the scroll bar reappears ...
I use KDE on Fedora 40 with the tuxguitar package provided with Audinux repository.
This package has been compiled with swt 4.26.

**Comment by guiv42** [comment]
Yep, this is purely intentional.

You can fin more detailed explanation in #403. I spent a lot of time on this performance issue. Basically the scrollbars induce a very significant performance issue with recent versions of SWT.

**Comment by ycollet** [comment]
OK. I used the scroll bar to recenter the score during pause ...
I will try to find another solution :)

**Comment by guiv42** [comment]
Sorry I don't understand.
> I used the scroll bar to recenter the score during pause ...

The scrollbar(s) is (are) supposed to be visible when you pause

**Comment by ycollet** [comment]
I play guitar while reading the score and with tuxguitar playing in the background.
Some scores have large part while I am not playing and I use to recenter the score during these phases.

**Comment by guiv42** [comment]
OK, understood. Sorry if the removal of scrollbars makes it more complicated for you, I could not find any better solution to this perf issue.

A possible solution to your use case: use "go to next marker" action? (default shortcut Alt+Right)

**Comment by guiv42** [comment]
I just restored the scrollbar(s), with an alternative fix for perf issue #403, see #557.
Issue can be closed.

**Comment by ycollet** [comment]
Thanks a lot !
