### ISSUE TITLE
checkable buttons do not remain checked (JFX)

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#51]
In Linux/JFX configuration all UIToolCheckableItem  do not remain "checked" visually: when clicked, they come back to their original aspect once the mouse leaves the control.
see video example with tied note:

https://github.com/helge17/tuxguitar/assets/129443524/3f9c1b46-9ca9-4fde-a8e5-e2fc1dd08e15

comparison with swt, "tied note" control remains 'checked':

https://github.com/helge17/tuxguitar/assets/129443524/c9594fe0-01da-4795-be99-66728a78771e

All controls of these type are concerned, which can be somehow confusing. For example, see above in the videos: both "voice1" and "voice2" buttons permanently have the same aspect in JFX config. So, user cannot know which voice is currently being edited.
not tested on other platforms

**Comment by helge17** [comment]
Fixed in 42f0ea1f72c72e95598a48f507524612fe08eb07.

**Comment by guiv42** [comment]
thanks!
