### ISSUE TITLE
Theme change not applied - Stuck on Oxygen theme

### ISSUE THREAD

**Issue by Antyss77** [helge17/tuxguitar#514]
When attempting to change the theme from "Oxygen" to another theme, the modification is not applied. The theme remains stuck on "Oxygen" despite the configuration menu showing that the new theme (e.g., "Oxygen Dark") is selected.

**Comment by guiv42** [comment]
Hi.
Could you please provide more details, so I can analyze? Which version of TuxGuitar, version of operating system, detailed procedure (step by step), screenshot or video... whatever could enable me to reproduce.
In my config it works fine: TuxGuitar 1.6.4, Linux openSuse tumbleweed (KDE, wayland), see video below.

A few details about skins:
- whatever the skin (light/dark), tablature always has white background and black foreground
- skin changes icons, and icons *foreground color*
- *background color* of icons, menus, etc, is supposed to be set by *the operating system*, not by TuxGuitar. If you are using Windows it does not work, see known issue #27

video in my config:

https://github.com/user-attachments/assets/e191bd2a-fe43-464e-ae6e-5fc5f5b033d1

to see the black background of buttons, toolbars, icons, etc, I would need to change my desktop setting from Linux/KDE.

**Comment by Antyss77** [comment]
> Hi. Could you please provide more details, so I can analyze? Which version of TuxGuitar, version of operating system, detailed procedure (step by step), screenshot or video... whatever could enable me to reproduce. In my config it works fine: TuxGuitar 1.6.4, Linux openSuse tumbleweed (KDE, wayland), see video below.
> 
> A few details about skins:
> 
> * whatever the skin (light/dark), tablature always has white background and black foreground
> * skin changes icons, and icons _foreground color_
> * _background color_ of icons, menus, etc, is supposed to be set by _the operating system_, not by TuxGuitar. If you are using Windows it does not work, see known issue [TuxGuitar doesn't pick up Win10's theme settings (dark theme) #27](https://github.com/helge17/tuxguitar/issues/27)
> 
> video in my config:
> 
>  skins.mp4 
> to see the black background of buttons, toolbars, icons, etc, I would need to change my desktop setting from Linux/KDE.


Everything's fine so I didn't understand why it didn't change the background, thanks for that.
