### ISSUE TITLE
Restart required to update solo/mute icons when changing theme

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#53]
When you change the theme, the solo/mute icons introduced with commit [d4f9871](https://github.com/helge17/tuxguitar/commit/d4f98718bc763f701a6cfa06b68adddfba81673b) are only updated after restarting TuxGuitar.

**Comment by guiv42** [comment]
Can this issue be closed?

**Comment by helge17** [comment]
Works, thanks!
