### ISSUE TITLE
Flags on track table header are not refreshed unless the mouse move on the header line 

### ISSUE THREAD

**Issue by vincentT** [helge17/tuxguitar#531]
When scrolling horizontally in the track table, flags in the header are not refreshed unless the mouse move on the header line.
I'm on Windows, tested on master
Adding this at the end of TGTableRow init method works but probably not optimal
```
this.painter.addPaintListener(new UIPaintListener() {
	@Override
	public void onPaint(UIPaintEvent event) {
		table.getColumnCanvas().getControl().redraw();
	}
});
```

**Comment by guiv42** [comment]
It's a bit surprising, this behavior is not reproduced in Linux environment (TuxGuitar 1.6.4, Linux openSuse tumbleweed)

**Comment by guiv42** [comment]
That should be OK now

**Comment by vincentT** [comment]
Indeed 👍 , tested it on master

**Comment by guiv42** [comment]
thanks for the test!

**Comment by vincentT** [comment]
Thanks for the fix !
