### ISSUE TITLE
Interface doesn't stay still when scrolling

### ISSUE THREAD

**Issue by 10b14224cc** [helge17/tuxguitar#534]
When I scroll, the interface doesn't stay in the page position I have chosen, but instead goes wherever it wants.

It is impossible to work like that.

Here is a screencap:

https://github.com/user-attachments/assets/82218794-abaf-4338-afa9-51c7269efcaf

I have tuxguitar 1.6.4 on Arch Linux

**Comment by guiv42** [comment]
precision to reproduce: page layout, multitrack song, score edition mode

**Comment by guiv42** [comment]
bug already present in TuxGuitar 1.5.6
@10b14224cc : as a workaround until I can find what's going on, I suggest
- using selection mode (if you are creating notes, create them in the tablature with keyboard, instead of score and mouse)
- or switching from track to track using track table

**Comment by guiv42** [comment]
Should be fixed by #535

**Comment by 10b14224cc** [comment]
Seems to work

**Comment by guiv42** [comment]
re-opening issue. Fix implemented by #535 has unacceptable side effects => reverted

**Comment by guiv42** [comment]
Another attempt to fix issue is now implemented (#538)
Hopefully both this issue and #536 should be fixed now

@10b14224cc : thank you for reporting this issue, and for your support for testing. I must admit I'm a bit surprised this bug has been present for such a long time without anyone complaining

**Comment by 10b14224cc** [comment]
Seems to work
