### ISSUE TITLE
Other notes are modified

### ISSUE THREAD

**Issue by 10b14224cc** [helge17/tuxguitar#536]
When I go to the last line of the tablature, and insert or delete a note, the note is inserted/deleted on the previous line

https://github.com/user-attachments/assets/34fa111b-2f35-4c7a-866d-f42060aa0df8

**Comment by guiv42** [comment]
Could you please precise which TuxGuitar version?

**Comment by guiv42** [comment]
PR #535 was reverted, so I re-opened #534
I think this issue shall be closed.

**Comment by 10b14224cc** [comment]
Seems to work
