### ISSUE TITLE
Using click and drag + copy and paste breaks rhythmic division in subsequent bars

### ISSUE THREAD

**Issue by buryoutougen** [helge17/tuxguitar#545]
Example to reproduce:

- create a new tab with 2 bars
- put a quarter note in the first bar and a whole note in the second bar
- select the quarter note and copy it
- paste it somewhere in the first bar

The whole note in the second bar changes into a quarter note tied to a dotted half note. It seems to affect both notes and rests in all subsequent bars, by the way.

**Comment by guiv42** [comment]
precision: reproduced with Tuxguitar 1.6.4

**Comment by guiv42** [comment]
Thank you @buryoutougen for characterizing this issue. I've been "polluted" several times by this phenomenon without understanding what caused it. The damaged measures can be very far away when pasting, even off-screen, so such effects can be seen very late after the problem really occurred.

Once *again*: we shall be very cautious when re-using code from 2.0beta fork. After re-reading the code, I just tested with multiple voices: this can lead to very weird results, including invalid measures...

Complete re-writing of "paste selection" feature in progress.

**Comment by guiv42** [comment]
see video: the bug mentioned in this issue + an illustration of the multi-voices issue. This ends up with 1 half + 3 quarters in a 4/4 measure

https://github.com/user-attachments/assets/01bd38e5-3f79-41f3-b48e-2f31101d7c1f

correction coming

**Comment by guiv42** [comment]
That should be better now.
Implementation is quite complex, so I would not be surprised if there are still some bugs in corner cases.
Hopefully eventual side effects -if any- should remain local.

**Comment by guiv42** [comment]
Fix is available from pre-release [2024-10-23](https://github.com/helge17/tuxguitar/releases/tag/2024-10-23-master), **in master branch**

**Comment by buryoutougen** [comment]
Looks fine to me, I tested it a bit and I don't get damaged bars anymore.
