### ISSUE TITLE
Test fails in tuxguitar-next (TestLetRing.java)

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#558]
Currently I get the following error when building TuxGuitar for Linux with `misc/build_tuxguitar_from_source.sh -l`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project tuxguitar-lib: Compilation failure
[ERROR] /path/to/Software/TuxGuitar/1.x/dev_tg-next/common/TuxGuitar-lib/src/test/java/org/herac/tuxguitar/player/base/TestLetRing.java:[191,52] cannot find symbol
[ERROR]   symbol:   method getFirst()
[ERROR]   location: variable events of type java.util.List<org.herac.tuxguitar.player.impl.sequencer.MidiEvent>
[ERROR] -> [Help 1]
```

Building only works if I add the option `-DskipTests` to mvn and when I additionally comment out the test below `// look for 1st note of measure` in common/TuxGuitar-lib/src/test/java/org/herac/tuxguitar/player/base/TestLetRing.java.

**Comment by guiv42** [comment]
Sorry for that. I thought I had fixed it already, but it was in the wrong branch (96012364c84421a3b67aa42363f40b2e20384856). Fix coming

**Comment by guiv42** [comment]
That should be OK now

**Comment by helge17** [comment]
Thanks!
