### ISSUE TITLE
Zooming in changes view position

### ISSUE THREAD

**Issue by 10b14224cc** [helge17/tuxguitar#568]
When I zoom in, the view position is changed and I get lost.

See attached video.

I use commit 721ad92e416ade4d2447b2ba5615fc7f140235e2 due to #534

**Comment by 10b14224cc** [comment]
https://github.com/user-attachments/assets/e88c439a-d4a2-485a-965d-a4bbcc72435d

**Comment by guiv42** [comment]
That should be better now

**Comment by 10b14224cc** [comment]
yes it works perfectly now, also when changing tracks (which I were going to report as well).

Thanks!
