### ISSUE TITLE
There is no "Java Sound Api plugin"

### ISSUE THREAD

**Issue by 10b14224cc** [helge17/tuxguitar#569]
The [documentation](https://www.tuxguitar.app/files/devel/desktop/help/tools_sound.html) says that if the "Java Sound Api plugin" is enabled, in the Sound tab of the Tools → Settings dialog you can choose "Java Sound Synthesizer" in the Midi Port list.

I have the plugin enabled, but there is no "Java Sound Synthesizer" in the list.

![image](https://github.com/user-attachments/assets/1658683e-6555-4469-a0c2-3e5484216516)

![image](https://github.com/user-attachments/assets/4bdf3b76-b80e-4760-b204-4d2de6601d34)

**Comment by helge17** [comment]
Thanks for the hint! "Gervill" is the Java Sound Synthesizer. Commit f3b24953bb5dbc872c2fdaf36c8e6a6da39669eb updates the doc.
