### ISSUE TITLE
Double icons on task bar

### ISSUE THREAD

**Issue by MaximusMMV** [helge17/tuxguitar#572]
I think this bug only appeared on the latest version 1.6.4.
Everytime I open Tux I get 2 icons on the task bar!
#Win10

![image](https://github.com/user-attachments/assets/b49160e1-90b8-4105-abbf-605332bb0186)

**Comment by guiv42** [comment]
Definitely I don't like these configuration-specific issues: I don't reproduce it on my Win10 configuration, with 1.6.4 (standalone version)

**Comment by MaximusMMV** [comment]
I managed to fix this! The thing was everytime a new Tux appeared I just installed it on top of the previous version using the installer and this worked fine, but for some reason 1.6.4 produced the double icon issue. I uninstalled it and used CCleaner, reinstalled 1.6.4 and boom: issue solved!
Too bad it didn't solve the freezing issue that I also commented on...

**Comment by guiv42** [comment]
OK, good, thanks
can this issue be closed?

**Comment by MaximusMMV** [comment]
Yes! Though I dunno how the Tux installer works: does it uninstall the previous version automatically or just overwrite the old files? 'Cos apparently something was left behind from 1.6.3 when updating to 1.6.4... 'Cos this had never happened before.

**Comment by guiv42** [comment]
I don't know (I'm on Linux). I would just recommend to uninstall old version before installing a new one.

**Comment by helge17** [comment]
I also noticed that all installed versions of TuxGuitar show up separately in the Windows App list. Commit b9ccf208a63a1a845eb373cf4c34babe40b0d91e should fix this.
The solution is described [here](https://releases.installbuilder.com/installbuilder/docs/installbuilder-userguide/_updates.html).

**Comment by MaximusMMV** [comment]
> I also noticed that all installed versions of TuxGuitar show up separately in the Windows App list. Commit [b9ccf20](https://github.com/helge17/tuxguitar/commit/b9ccf208a63a1a845eb373cf4c34babe40b0d91e) should fix this. The solution is described [here](https://releases.installbuilder.com/installbuilder/docs/installbuilder-userguide/_updates.html).

Yes, I noticed it when trying to solve the issue. I had like 4-5 diff Tux installs listed on Windows (but only 1 Tux directory thou)... That's why I did the CCleaner, then intalled Tux again, which solved it.
