### ISSUE TITLE
Install breaks windows

### ISSUE THREAD

**Issue by peternschmit** [helge17/tuxguitar#575]
I saw this post on r/opensource recently.

[Tuxguitar just murdered my pc.](https://www.reddit.com/r/opensource/comments/1gfcwn1/tuxguitar_just_murdered_my_pc/)

Has anyone else experienced this?  I unfortunately can corroborate; Tux just bricked my Windows 11 install.

**Comment by helge17** [comment]
Just checked tuxguitar-1.6.4-macosx-swt-cocoa-x86_64.app.tar.gz, tuxguitar-1.6.4-windows-swt-x86_64-installer.exe and tuxguitar-1.6.4-windows-swt-x86_64.zip with MS Defender on an up-tp-date Windows 10. Installed tuxguitar-1.6.4-windows-swt-x86_64-installer.exe, compared the files on Github with the originak files on my build system and compare sha256 sums. Currently I cannot find any problem or mismatch.

Did you check the sha256 sums of the downloaded files?

My files are not signed with an official developer key, maybe this makes them "suspect" (see #411)?

Detailed error messages would be very helpful.

I'll redo the tests on Windows 11 in the next days.

**Comment by helge17** [comment]
I have checked all 1.6.4 files with VirusTotal: As of today, all files have been marked as clean by all available security vendors.

[tuxguitar-1.6.4-freebsd-swt-amd64.tar.gz](https://www.virustotal.com/gui/url/d81290f75685562447d61c60e823ad8eb559e7f82942593cdf09d36aef2211a8)
[tuxguitar-1.6.4-linux-swt-amd64.deb](https://www.virustotal.com/gui/url/1578560a3ae66d2ed8702610a78b2ca99d30616aa3cfd4012210e1926e034255)
[tuxguitar-1.6.4-linux-swt-amd64.tar.gz](https://www.virustotal.com/gui/url/daa193a4c8b36a3e3aae97f8513cb69b7abf8ab6d68b5afbb5d4aab2882a3947)
[tuxguitar-1.6.4-macosx-swt-cocoa-x86_64.app.tar.gz](https://www.virustotal.com/gui/url/d1d04eba7b98cbff5b537fa7867c47284060497a086b9aa9c74722d6a439ab35)
[tuxguitar-1.6.4-windows-swt-x86_64-installer.exe](https://www.virustotal.com/gui/url/9c2f555ffed4cdb38a3475a38512db8e3d2439c3a55b65cfd119b260b4818031)
[tuxguitar-1.6.4-windows-swt-x86_64.zip](https://www.virustotal.com/gui/url/6b9eabf1406cb76ea3ed5d2b93cad28df448e57564c6f44d400883a704fb8a41)
[tuxguitar-1.6.4_linux-swt.x86_64.rpm](https://www.virustotal.com/gui/url/89da1fbac08ac4b6f667a44b79a126c11578a436fcd4e3d60f8ebf11411d59b8)
[tuxguitar-android-1.6.4-release-signed.apk](https://www.virustotal.com/gui/url/0f74703ae18ff6f0fc3dcff9526a025bbe6f0ceed7f28f210d590ae00616c2d9)

I also virus-checked and installed the file tuxguitar-1.6.4-windows-swt-x86_64-installer.exe on Windows 11 23H2: No problem.

The user on Reddit confirmed that the security warning on his PC was only related to the missing digital signature of the installer and not to a virus warning.
https://www.reddit.com/r/opensource/comments/1gfcwn1/comment/luh0x3l/

We are trying to make the Windows installer in the tuxguitar-next branch more robust, e.g. with commit b9ccf208a63a1a845eb373cf4c34babe40b0d91e. Other than that, I don't know how to help here at the moment without more details. I suspect that the problem occurred more or less by accident when installing TuxGuitar. If you search the internet, you'll find tons of cases and reasons why Windows 11 hangs on boot.

**Comment by peternschmit** [comment]
My issue didn't stop at the warning, though I did experience that too.  For me, after the install, any subsequent boots into Windows 11 stopped at "Automatic Repair," which failed to resolve the issue, leaving me stuck.  In the end I just reinstalled the OS.  Unfortunately I don't have any error messages or traces of what occurred, so I'll just close this conversation and consider it a fluke.
