### ISSUE TITLE
metronome not working 1.6.5

### ISSUE THREAD

**Issue by faetcaet** [helge17/tuxguitar#606]
Hello,
i recently updated to tuxguitar 1.6.5. if i turn on the Metronome and Count-in and play the tab, the count-in is audible, while there is no metronome click when the track is running.
Thanky for checking!

**Comment by ycollet** [comment]
I feel the metronome is disabled when the drum track is not empty. I can hear the metronome, but only when the drum track plays no note.

**Comment by guiv42** [comment]
I cannot reproduce this issue, could you please share your configuration?

**Comment by ycollet** [comment]
I am on Linux, using pipewire-jack at 48000 Hz / buffer size 256. Using fluidsynth 2.4.0 + tuxguitar / fluidsynth plugin with the same kind of settings (jack / 48000 / 256) ...

**Comment by guiv42** [comment]
should be ok now

**Comment by guiv42** [comment]
@faetcaet , @ycollet : could you please test if it's OK on latest pre-release? (>= 2024-12-17)

**Comment by faetcaet** [comment]
it works on 1.6.6beta1. Thank you for your work!
