### ISSUE TITLE
Play on macOS sometimes stops at end of first played measure

### ISSUE THREAD

**Issue by SimplyTheOther** [helge17/tuxguitar#615]
Hi,

I recently upgraded from TuxGuitar 1.6.0 to 1.6.6 on macOS, Sonoma 14.3, Apple M1 Pro (i.e. arm64). 

When I tried to edit an existing tab, I've noticed that sometimes playback cuts off at the end of some measures. This does not seem to occur to all measures or consistently affect the same measures.

The attached video shows playback from one measure cutting off twice in a row, and then playback from the subsequent measure behaving normally. Sorry for the bad video quality, I had to downsample it for GitHub to accept it.

I have not configured any looping: the playback is on the default "Simple Mode" at 100% tempo.

https://github.com/user-attachments/assets/966e243a-1ff0-4018-bffe-1755ef8f5550

The tab I was editing can be accessed here (GitHub wouldn't let me upload it): https://drive.google.com/file/d/1T_6AxEDctGj3Mi5qS8lYCMC8URgBKXYC/view?usp=sharing

EDIT: turning on looping, playing, then turning it off and playing again appears to at least sometimes resolve this issue, as can be seen in the video below:

https://github.com/user-attachments/assets/9e64f209-aaeb-48e1-aca5-5edcdb9be22f

**Comment by guiv42** [comment]
I think I have understood... and it does not seem to be linked to the player.

When you *click on* one beat and hit play, it plays *the song* starting from caret position.
When you *click and drag a little* it *selects* one beat. There, if you hit play it only plays the selected measure. In fact this is the expected behavior (play only selection when something is selected)

@SimplyTheOther : can you confirm?

If so, I would say that your problem is exactly the one described in #293: click and drag is too sensitive. Sometimes you just want to *click* on one beat and it happens to get *selected*.

**Comment by SimplyTheOther** [comment]
Thanks for the quick reply. 

I think you're right - the playback appears to play only the given measure if the blue "beat" selection is made, while it appears to play everything if only the grey "box" selection is made. Thanks for the heads up, I'll be more careful in clicking from now on.

Is this beat selection mechanism a new feature? I don't ever recall being able to select beats in this way in "classic TuxGuitar".

**Comment by guiv42** [comment]
Yes, this "click & drag" selection feature is quite recent. It's been implemented a long time ago (around 2016), but it was merged in master branch only with 1.6.0.
"Play selection" is clearly not the main added value. This ability to select multiple beats can be very useful: copy/paste, change notes attributes (e.g. velocity), apply effects (staccato, palm mute...), shift 1 string up/down, etc.

Anyway, thanks for your feedback. Can this issue be closed?
I think I will re-open #293: looking at your videos, when you *select* one beat I have the impression your intention was only to *click* on beat (i.e. not to *click and drag*).
