### ISSUE TITLE
MacOS playback error: First note doesn't sound sometimes. Also please bring the old soundfont as option

### ISSUE THREAD

**Issue by Sy256** [helge17/tuxguitar#618]
Hey I've been busy and havent checked in on this in awhile but today i got some downtime to start working on a tab and i downloaded the newest version 1.6.6 hoping to solve this bug which is the first note of the selected measure just doesn't play sometimes. This is M1 mac and i was hoping that'd be fixed by now, i brought it up a year ago. I know mac/m1 is not the priority but this is a really bad bug, i basically have to stop/play playback over and over until the first note sounds out. sometimes it takes a few seconds sometimes a whole min to hit the scenario where it plays through flawlessly. Another workaround is to add a empty measure to the beginning of whatever measure im trying to play to allow the playback to start in there, but i dont want to keep doing that.

I also do not like the new default sounds please bring back the option of switching to the old soundfont. Or maybe its just that the new default one seems to transpose everything by -12, i dont know if its a new soundfont.

Here's a short vid that shows all that's wrong https://youtu.be/m808nGP30ZI?si=e9cbs-X682fBmYTZ
The first one im using is 2023-10-01-snapshot. I like the sounds used in that.

I haven't been able to check out all the rest of whats been added since I last checked in yet, I just downloaded this trying to avoid the bug. If you need me to test anything else on mac while I'm in there please let me know.

Thank you!

**Comment by guiv42** [comment]
Two different problems
1. first note doesn't sound: #77 is still open, it means no one could fix it yet. Insisting and re-opening the same issue does not help.
2. sound fond: I don't understand your request, since the sound font provided with TuxGuitar did not change since years

I just don't see what we could do here...

**Comment by helge17** [comment]
1. first note doesn't sound: Please continue in #77
2. sound font: I strongly suspect that these are just different settings, please compare _Tools -> Plugins_ and _Tools -> Settings -> Sound_.

**Comment by Sy256** [comment]
Sorry to put 2 issues in the same topic. Closing this one and redirect to 

https://github.com/helge17/tuxguitar/issues/621
and 
https://github.com/helge17/tuxguitar/issues/77
