### ISSUE TITLE
change default track instrument and clef

### ISSUE THREAD

**Issue by devNat0** [helge17/tuxguitar#619]
How do I change the default instrument "Steel String Acoustic Guitar" and clef?

If I use a different instrument, everytime I open TG I have to change the track instrument, then change Composition>Clef to bass for example.

It doesn't seem to be mentioned in the [documentation](https://www.tuxguitar.app/files/1.6.6/desktop/help/editing_song.html)  unless I'm missing something, no mention of how to use tuxguitar.cfg, and not in settings.

I only know that [this code](https://github.com/helge17/tuxguitar/blob/8e4c37bbb43c0d0028a0898a4aff63866bfe74c6/common/TuxGuitar-lib/src/org/herac/tuxguitar/io/tg/TGSongReaderImpl.java#L145) sets the default track name which is called by [that](https://github.com/helge17/tuxguitar/blob/8e4c37bbb43c0d0028a0898a4aff63866bfe74c6/common/TuxGuitar-lib/src/org/herac/tuxguitar/io/tg/TGSongReaderImpl.java#L130). I don't understand the architecture of who calls this and why it needs to be a readByte instead of being passed as a param.

**Comment by guiv42** [comment]
Create one song with all default attributes you want (tracks, instruments, etc), and save it somewhere on your machine.
Then, in TuxGuitar, click menu "File -> Set custom template" and browse to your song.
That should do the job

**Comment by devNat0** [comment]
Thank you for your help and time. I apologize for using up your time by not reading all the [documentation](https://www.tuxguitar.app/files/1.6.6/desktop/help/detail_file_edit.html) thoroughly.

**Comment by guiv42** [comment]
No need to apologize, it's not always easy to find the appropriate information in the user doc.
Good to know this feature is useful :)
