### ISSUE TITLE
random sound quality issue

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#8]
Hi,
I have a random sound quality issue with release [2023-03-30](https://github.com/helge17/tuxguitar/releases/tag/2023-03-30) . Running several times in sequence the same `tuxguitar.sh` from the same shell may show the issue, or may not. Estimation of occurrence is about 50% (I consider one configuration is OK if I can run it 10 times without the problem). When the problem occurs, sound is just unusable.
Since the issue never occurs with TG 1.5.6, I performed a dichotomy, which finally led me to [this commit](https://github.com/helge17/tuxguitar/commit/54353a1a24aa6ddbbb9935439f0c6f0f2c5d0305).
I don't know what "icedtea-sound" is and where it comes from, but it really looks its removal is the cause of the issue in my configuration : if I manually copy the files `icedtea-sound.jar` and `libicedtea-sound.so` from 1.5.6 in the `/lib` folder of release 2023-03-30 the problem *seems* solved. Yes, I prefer to say "*seems solved*", because randomness of this issue already led me once to erroneous conclusions... However I could run this configuration 30+ times without any problem.
With the original 2023-03-30 release, I can always change the plugins and sound settings to configure sound with fluidsynth, however it's just a workaround, and sound is supposed to work out of the box (I may not be the only one experiencing this issue).
note: I'm running the linux-x86_64 version with OpenSUSE tumbleweed, issue is identical in both swt and jfx configurations.
I have no idea about a possible solution to that problem, since I don't know what icedtea-sound is, and I don't know either why it was removed.
If anyone has an idea about a possible fix, the only support I can provide is testing!

**Comment by helge17** [comment]
Thanks for the analysis! I can reproduce the problem on Debian Bullseye and also Bookworm.
icedtea-sound.jar/libicedtea-sound.so are included as binaries in 1.5.6, without the source code. As far as I found out, icedtea-sound is a very old, unmaintained software, difficult or impossible to compile on newer systems. That is the reason why I deleted the files from my version.
So a workaround could be to add both files back as binaries. But in the long run, icedtea-sound has to be replaced somehow, and using binaries without source code is not an option for most distributions like Debian.
The problem only occurs with the audio settings "TuxGuitar Sequencer / TuxGuitar Synthesizer".
Commit 8e8318e activates the "Java Sound Api Plugin" and sets the sound to "TuxGuitar Sequencer / Gervill" by default on Linux. So for new installations the sound should work right now. I hope this is an acceptable workaround until someone can get the TuxGuitar Synthesizer working without icedtea-sound.

**Comment by guiv42** [comment]
Thanks for your fast answer. As far as I could test, your workaround definitely seems to fix the issue :+1: 
I was a bit surprised to find these binaries directly included in 1.5.6, without being able to easily find the associated source. So I fully agree with you, adding back those binaries does not seem an acceptable solution.
Anyway, I must admit I do not fully understand this workaround. I can see that `midi.port` is now set to `Gervill`, but in the ui it did not change anything: sound configuration  window still displays "Port MIDI = TuxGuitar Synthetizer". So what do you mean with 

> until someone can get the TuxGuitar Synthesizer working

?
From my point of view, with this configuration it seems to work...

**Comment by helge17** [comment]
The commit 8e8318e should activate the "Java Sound Api Plugin" and set the sound to "TuxGuitar Sequencer / Gervill" for new installations, more precisely if there is no configuration in ~/.tuxguitar-1.5.6/ yet. Then also the sound settings in the GUI should show "Port MIDI = Gervill". The result should be the same as if you set up TuxGuitar manually this way.

Maybe TuxGuitar is confused if there is already a configuration in your $HOME. You can try to click "Defaults" in the sound settings or stop TuxGuitar, delete the directory ~/.tuxguitar-1.5.6/ and then start it again.

By "until someone makes the TuxGuitar Synthesizer work" I mean that probably the Java code has to be adapted to work without icedtea-sound. I probably won't be able to do that.

**Comment by guiv42** [comment]
Yep you're right, I was mistaken by the ~/.tuxguitar file.
Thanks for your answer, that's clear. No idea either about that Java code...
