### ISSUE TITLE
missing icon in toolbar for "Let Ring" effect

### ISSUE THREAD

**Issue by guiv42** [helge17/tuxguitar#87]
"Let Ring" effect is only accessible through menu Beat/Effects or shortcut, but there is no associated icon in toolbar.

note: description of this effect is also missing in [help](https://github.com/helge17/tuxguitar/blob/master/TuxGuitar/share/help/edit_effects.html) section. Absence of this icon probably explains why it has not been included in help rework (20e93610fc224f6ced785be6c0b4fe142d764f97)

**Comment by helge17** [comment]
2cb0bc38cf4a5100ce5a0a7d606aaa71e17db090 adds a short description for "Let Ring" to the [help](https://github.com/helge17/tuxguitar/blob/master/TuxGuitar/share/help/edit_effects.html) file.I suggest adding the missing icon after the 1.6.0 release, the icons and skins need a rework anyway.

**Comment by helge17** [comment]
Commit cf18c0e15625f471f8d7b49bf8566d194768191f adds the icon for "Let Ring" to the edit toolbar. Close this issue?

**Comment by guiv42** [comment]
I was about to close it, however I just noticed that a few screenshots need to be updated in the help section (including "let ring", but also copy measure, etc). 
I can do it if you want.

**Comment by helge17** [comment]
Sorry, forgot about that. I will update the snapshots.

**Comment by guiv42** [comment]
Thanks!
