### ISSUE TITLE
Stop and resume playback from original spot

### ISSUE THREAD

**Issue by alejandro6626** [helge17/tuxguitar#92]
Up to version 2023-05-27 when stopping playback (e.g. using spacebar) the active measure or cursor goes back to the spot from where playback was started, meaning that if you hit play or press spacebar again, playback will start over again from the same place, unless you manually change the current measure or starting point. This is extremely useful for practicing passages over and over again (just hitting spacebar) and was always a good feature of tuxguitar that has always existed. However, from that version onwards, when you hit stop and then you resume, playback will continue from where it left, meaning that if you want to practice a section again, you need to manually look for the measure where it starts which is not practical for practicing, specially if you're standing with a guitar hanging from your shoulder.
I think that the old behaviour should be restored or that at least it can be selected from preferences.

**Comment by guiv42** [comment]
We're entering a subjective area here: this new behavior was implemented following users' requests. See [here](https://sourceforge.net/p/tuxguitar/discussion/522984/thread/65c8acf27b/) and [here](https://sourceforge.net/p/tuxguitar/feature-requests/101/).
I also considered old behavior inconsistent: it wasn't logical to have "pause" and "stop" buttons behaving identically.
Note: this new behavior is consistent with Android app.

That being said, your use case is relevant, and there might be a way to address it also. A possible solution could be to create a new action "play/stop", accessible through a shortcut. 
This way one could allocate spacebar either to play/pause or to play/stop actions.

What do you think?

note: not yet evaluated the complexity of such a feature

**Comment by alejandro6626** [comment]
Yes, it's subjective. However I noticed this change immediately as I've used Tuxguitar for a very long time and I could say the behavior has been always like that as far as I remember.

In my case, I use Tuxguitar as a backing track to practice guitar solos, so I need to stop and resume from the same spot all the time, thousand of times, and doing that with the spacebar was really helpful.

Assigning a shortcut key to the stop action works, e.g. "c", i just need to start play mode with spacebar and then stop with "c". It could take a while for me to get used to it, as I probably will instintively hit spacebar to stop at the beginning.

As you say, space bar is assigned to play button, and the play button turns into pause, so spacebar is truly assigned to "play/pause" and not "play/stop", which doesn't exist. (Actually in the shortcuts Window, the instead of "play" action it should say "play/pause"). If you create a play/stop action, then I could move the spacebar away from play/pause and assign it to the play/stop and everyone would be happy.

I do want to thank you for making Tuxguitar great, it's my main tool for doing what I love most, which is playing guitar. Thank you so much!!!

**Comment by Sy256** [comment]
I did not know what stars are and I just starred it myself hope that helps. Since you guys are looking into something that has to do with the playback function could you take a look at #77 see if there's anything that's effecting that? Thanks! It is moderately rare but when it happens it can make me lose focus on how the whole thing goes and where the next beat should be.

**Comment by guiv42** [comment]
The only question addressed here is what the behavior of the **cursor** should be when user hits spacebar (**pausing** or **stopping** playback). Issue #77 is linked to **sound** management when playback **starts**.
So these 2 issues are completely unrelated.

**Comment by guiv42** [comment]
Thank you @helge17 for merging and pre-release.

@alejandro6626 : feature is now available from 2023-08-23, could you please give some feedback, and close this issue if it seems OK for you?

**Comment by alejandro6626** [comment]
Hi, yes I'll test and give feedback as soon as possible. I did try to build from source but ran into errors in my Manjaro Linux, so I'll go for the released build. Thanks.

**Comment by alejandro6626** [comment]
It works perfectly, THANK YOU SO MUCH!!!

Honestly, Tuxguitar is the software I use the most in my free time since I found it ages ago. I though it was discontinued until I found that you guys are maintaining it and improving it. I think many people believe it doesn't get any more updates, your project definitely deserves more publicity and you guys a lot of credit. You have done a lot improvements to the software. Chapeau.

There are 700 million guitarists in the world, if 30% of them use some kind of software and 30% of them use Tuxguitar (because honestly there aren´t other options to GuitarPro), this piece of software could have 50+ million users. I don't know if you ever thought about it. Many (as I did until recently), ignore the existence of the improved releases you're putting together.

Thanks again. Spanish translation looks very good, so I don't think I can help with that...I'll try to give publicity to this repo in the ways I can.

**Comment by guiv42** [comment]
> Spanish translation looks very good, so I don't think I can help with that

If you could have a look at [the Spanish translation file](https://github.com/helge17/tuxguitar/blob/master/TuxGuitar/share/lang/messages_es.properties), there is still some job to do. Basically, all items related to the new features we have recently implemented in this repo need to be translated. Just look for lines starting with # character, there are quite many of them.
A basic example: the [play/stop action](https://github.com/helge17/tuxguitar/blob/868008ab70277b459acef37fa25d27c30e955d98/TuxGuitar/share/lang/messages_es.properties#L747C28-L747C28) just created following our discussion here (and as you mentioned above, it would also make sense to change "play" into "play/pause").
Also several items were added together with the "click & drag select" feature (e.g. see [here](https://github.com/helge17/tuxguitar/blob/868008ab70277b459acef37fa25d27c30e955d98/TuxGuitar/share/lang/messages_es.properties#L621C33-L621C33)), or the [custom user template feature](https://github.com/helge17/tuxguitar/blob/868008ab70277b459acef37fa25d27c30e955d98/TuxGuitar/share/lang/messages_es.properties#L57C6-L57C6)

> I'll try to give publicity to this repo in the ways I can

Thanks, that should help! We are currently preparing an "official" release of a 1.6.0 version, that could be a good opportunity to communicate and promote this repo.

Last but not least: could you close this issue since I understand that it's solved?

**Comment by alejandro6626** [comment]
Do I simply edit the Spanish Translation File in Github and remove the # characters?

I surely can do that, sorry I've never used github, thanks.

**Comment by guiv42** [comment]
Thanks for your proposal!
Yes, updating translations is as easy as that: just fill in the text after the "=" sign and remove the leading "#" (all lines starting with "#" are ignored and corresponding text is displayed in English). If the name of the string to translate is not clear enough, refer to it in the [English version](https://github.com/helge17/tuxguitar/blob/868008ab70277b459acef37fa25d27c30e955d98/TuxGuitar/share/lang/messages.properties).
You can even test your modifications it locally without re-building the app, just overwrite your local file in "[TuxGuitar installation path]/share/lang" and restart TuxGuitar.
To submit your contribution:
- if you plan to contribute on a regular basis, have a look at [this tutorial](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
- if you think it's just one-shot you can simply push the updated file in a discussion here, we can do the job to merge it in the code base

**Comment by alejandro6626** [comment]
I have almost finished completing the Spanish File, I've also corrected some spelling mistakes and I changed some terms to make them easier to understand for Spanish speakers. I tried to stick to guitar Jargon in Spanish, some terms are used in english, like hammer-on, so I've left them as they are, as everyone understands them and refers to them like that.
Before I submit it to you, one question:
The menu Beat, should actually be called "Note", since all options there are used to change notes and notes' behaviour. Beat refers to the strong time in a bar, it's something different.
Spanish translation is currently "Pulso" which means "pulse" or "beat" but again. I believe the word Pulso and also Beat in English is wrong, but before changing it in Spanish to Note I wanted to check with you, since it's all over the place. Let me know what you think.
I also couldn't find the strings for the Tuner and Tuner options.

Thanks

**Comment by guiv42** [comment]
I don't know what's best about "Beat" menu, your remark makes sense. It's always difficult to change something that has been like this for years, even if you think the result is better. There is a risk some users may prefer it as it was before. Just look at our discussion above about cursor position! So, for this reason I would not change the English version.
I'd say just do whatever you feel best (just for information: in French version "Beat" menu is currently translated as "Note")

Forgot plugins translation files: they are managed independently.
For the Tuner you can find the translation files [there](https://github.com/helge17/tuxguitar/tree/master/TuxGuitar-tuner/share/lang), yet there is none in Spanish.
Spanish translation files are also missing for [batch file converter plugin](https://github.com/helge17/tuxguitar/tree/master/TuxGuitar-converter/share/lang), and [Jack plugin](https://github.com/helge17/tuxguitar/tree/master/TuxGuitar-jack/share/lang)

**Comment by alejandro6626** [comment]
In Portuguese it's also "Note" so I'll change to Note in Spanish, looks a lot better.

Regarding cursor position, when you hit stop and it goes back to the measure you had started playback at, my preference is that the whole measure is played again, even if cursor was on some note in the middle of the measure.
Actually when you hit play, it will take it from the top of the measure, meaning that when you hit stop and play again, it makes sense that it works that way. Currently It does work that way so it's fine from my perspective.

In order to start playback you need some context, meaning that you need to start from the beginning of the bar, starting from a note in the middle will be kind of odd.

**Comment by helge17** [comment]
If you look at older snapshots of TuxGuitar (e.g. https://www.linuxlinks.com/tuxguitar/ or https://commons.wikimedia.org/wiki/File:Greenie_Linux_1.1a.png), you can see that the menu has been renamed from "Note" to "Beat", perhaps from version 1.1 to 1.2. I suspect that many translations are older and therefore still use the word for "Note". Julian probably renamed the menu to make it clearer that a beat can contain multiple notes, and that many actions in this menu affect all notes in a beat. Personally, I changed the term "note" to "beat" in the German and Italian translations (Note -> Taktschlag, Nota -> Battuta). But of course the terms leave some room for interpretation, and different languages may use them differently. Maybe it would make sense to split the menu into "Note" and "Beat", since in general the menus, icons and skins need restructuring, see e.g. #87.

**Comment by guiv42** [comment]
I like this idea, however it may not be so easy to split the menu between **note** actions and **beat** actions, as from software internal point of view the boundary is not that clear. For example, some effects are logically (or visually) attached to **beat**, while they are internally associated to **notes**. See this scenario:
- create a 6-strings chord
- put cursor on note on string 1, and associate "Palm Mute" effect
  "P.M" is displayed under the **beat**. From user point of view, the whole chord shall be palm-muted
  but internally, it's only associated to the single **note** on string 1:
- delete any note of chord on another string, palm mute is still displayed
- delete the note on string 1, palm mute disappears

**Comment by alejandro6626** [comment]
Please find the Spanish translation file. As Spanish speaker, I think it looks good.

I have appended at the bottom the Tuner, Batch File Converter and Jack Settings translations. I don't know if they should go there, but it works, Tuxguitar picks them up.

I have changed the Menu to Note, I truly don't think it's worth having two Menus. Most of the actions there apply to a Note or a set of Notes, so still makes sense.

Beat (Pulso) in Spanish looks too awkward to me. Also Tuxguitar is all about writing notes, so the Menu where most Note related actions are stored, should be called "Note" I believe. Also in GP the menu is called Note.

Hope this helps!

[messages_es.properties_alejandro6626_20230829.zip](https://github.com/helge17/tuxguitar/files/12470476/messages_es.properties_alejandro6626_20230829.zip)

**Comment by helge17** [comment]
Thanks for the Spanish translations! They are now part of release 1.6.0beta1 (commit 84f92aee474a7370544f2731f8acf47f08e82cd3).
